### ISSUE TITLE
compile error !

### ISSUE THREAD

**Issue by lilux618** [ProjectPhysX/FluidX3D#10]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/60692776/191946412-f416b3b6-70f8-4c4b-9c98-9875f3fb6ba4.png">
When I compile the program, I got an error like before., what's wrong with me?

**Comment by ProjectPhysX** [comment]
I think you have posted this issue to the wrong repository. This is not my code, I don't use CUDA.
This looks like the code of [jrwaine](https://github.com/jrwaine), see here: https://github.com/CERNN/VISCOPLASTIC-LBM
