### ISSUE TITLE
voxelize_mesh_on_device

### ISSUE THREAD

**Issue by syy-mudong** [ProjectPhysX/FluidX3D#103]
May I ask if the flag established through stl belongs to a solid boundary? May I use stl to establish a fluid node

**Comment by syy-mudong** [comment]
![image](https://github.com/ProjectPhysX/FluidX3D/assets/84362182/b0dfd350-8877-4153-9326-c3ad181468f1)
Can I create a new function to achieve the goal of using stl to construct fluid nodes by changing the fluid nodes here

**Comment by ProjectPhysX** [comment]
Yes.
The `flag` here sets the cell type inside the mesh geometry, by default solid (`TYPE_S`). You can also set it to `TYPE_F` instead to voxelize as fluid nodes- Make sure to enable the [`SURFACE`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/defines.hpp#L22) extension for this.
