### ISSUE TITLE
weird issue with the mercedes f1 car setup

### ISSUE THREAD

**Issue by angang213** [ProjectPhysX/FluidX3D#109]
i was doing an export of the mercedes f1 car scene when it all seemed to just.... disappear...

this issue is also present in interactive graphics mode.
it happens at around 700-800 ish time steps at 15,000MB but it takes more time steps the lower the grid resolution

https://github.com/ProjectPhysX/FluidX3D/assets/68238672/c3ebf0b4-fc95-4016-9b76-61b9c57a3133

https://github.com/ProjectPhysX/FluidX3D/assets/68238672/46f070fe-5b33-4149-9b92-b606541110a9

**Comment by ProjectPhysX** [comment]
I'm aware of this issue; it's a really challenging geometry and parameter range. The instabilities originate from the wheel hubs, where rotating geometry is next to fixed geometry. In the tight gaps on one side wheel rotation velocity is enforced, on the other side zero velocity. The high local shear rate results in some internal value to blow up to infinity and this propagates through the entire simulation grid as NaN (not a number).
