### ISSUE TITLE
Usage for Reinforcement Learning 

### ISSUE THREAD

**Issue by Pippo809** [ProjectPhysX/FluidX3D#114]
Hello
Have you aver explored the possibility of integrating this simulater in existing libraries (stable baselines or open-ai gym) and use it to train agents in a fluid environment?

**Comment by ProjectPhysX** [comment]
Hi @Pippo809,

that sounds like a super interesting and fun idea! AI-based training of physical creatures/agents moving/swimming in a water environment simulated in CFD. I think FluidX3D has the power to do the thousands of simulations that such training requires.

I myself plan to stay focused on developing and improving the solver itself, but I'd be happy to see others do such AI agent training applications with it, provided it is for research/education/hobby purposes.

All the best,
Moritz
