### ISSUE TITLE
Moving Solid Mesh

### ISSUE THREAD

**Issue by zzhou292** [ProjectPhysX/FluidX3D#116]
Hello,

Thank you in advance for any clues provided under this issue.

I am aiming to couple FluidX3D with Project Chrono to enable CFD simulation support for moving vehicles, as shown in this vid: https://www.youtube.com/watch?v=ueWIOOU1QfI&ab_channel=UWSBEL. 

For me I really just want to show the vehicle chassis, so the problem can be simplified into 'a solid and nondeformable mesh but it moves in the contained domain'. Is it possible to enable a moving mesh in the scene? 

Thank you again for answering! I cannot appreciate more!

Jason

**Comment by ProjectPhysX** [comment]
Hi @zzhou292,

moving objects are possible and require periodic re-voxelization. For your example, my advice is to export the rotation matrix and translation vector from your animation software to one or more files. Load these in FluidX3D (write a custom function for this using [`read_file`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/utilities.hpp#L3990)), and use them to periodically move/rotate the mesh, then re-voxelize and simulate a few tme steps following the [documentation](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#loading-stl-files).

Have fun!

Kind regards,
Moritz
