### ISSUE TITLE
How to save and resume simulations?

### ISSUE THREAD

**Issue by rodionstepanov** [ProjectPhysX/FluidX3D#119]
It seems I can save current data with
lbm.rho.write_device_to_vtk();
lbm.u.write_device_to_vtk();
but how to read it in order to continue simulation form the save data?

**Comment by rodionstepanov** [comment]
I agree the full checkpoints is too expensive but why don't take velocity field form stored data file and generate the density distribution functions as for an initial state?

**Comment by ProjectPhysX** [comment]
Yes you can do that, use the .vtk output of one simulation as starting conditions for another. A .vtk loading/import function is not yet implemented but you can reverse-engineer the [write_vtk()](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/lbm.hpp#L258)  storing/export function.
