### ISSUE TITLE
Feature request: integration with Blender3d 3.5.x-4.0a

### ISSUE THREAD

**Issue by Dmeerev** [ProjectPhysX/FluidX3D#123]
Woud be very nice if this software can integrate with blender. Current fluid/gas simulator - mantaflow is cpu only, has low multithreading rate, and painfully slow.

**Comment by ProjectPhysX** [comment]
Hi @Dmeerev,

FluidX3D is a standalone software with an integrated OpenCL rendering engine. The combining of multi-GPU fluid solver and custom multi-GPU enderer is what enables the real-time rendering capabilities in the first place, as the renderer has direct access to the raw simulation data in VRAM and no data has to be moved at all. Moving the rendering part to an external software like Blender would eliminate this benefit, making rendering about 100x slower and requiring hundreds of TeraByte hard disk space for storing simulation data. On top, Blender recently removed their OpenCL rendering backend, so it would not even be compatible. Thus I am not planning to integrate FluidX3D into Blender or make it a plugin.

Kind regards,
Moritz
