### ISSUE TITLE
Initialization sends unnecessary amounts of data to device

### ISSUE THREAD

**Issue by jansol** [ProjectPhysX/FluidX3D#126]
I noticed there is a lot of host->device traffic during init. This is likely generated by Memory constructors that initialize buffers to a constant value.

Some very noticeable speedups to FluidX3D startup could be achieved by using `clEnqueueFillBuffer` if the size of the type of a buffer element is one of `{ 1, 2, 4, 8, 16, 32, 64, 128 }` (the legal sizes for the pattern passed to that function). Similarly for the host copy `std::fill` *may* be faster than the currently used for loop as it can potentially use optimized compiler intrinsics.

**Comment by ProjectPhysX** [comment]
Hi Jan,

thank you very much for these suggestions!

I tried a simple case, 3x 2GB allocation:
- previously was 2.4s
- `std::fill` is 0.4s quicker
- `enqueueFillBuffer` is 1.0s quicker

Overall 2.4x faster. Amazing!
In FluidX3D with the additional initialization and sanity check loops, the overall speedup is less, in the order of ~8%.

I have committed this to the [OpenCL-Wrapper](https://github.com/ProjectPhysX/OpenCL-Wrapper/commit/1afa357bf8eb56106c3cc95dec80660ae826dec8) and [FluidX3D](https://github.com/ProjectPhysX/FluidX3D/commit/feef36d26966c78e3ac9a297b9341aa79ff96aff).

Kind regards,
Moritz
