### ISSUE TITLE
'class LBM' has no member named 'graphics'

### ISSUE THREAD

**Issue by andrewjosephlehmann** [ProjectPhysX/FluidX3D#129]
Hi, I am trying to compile an example provided in setup.cpp. Despite my best efforts, I continue to receive the same error stating: .../src/setup.cpp:520:13: error: ‘class LBM’ has no member named ‘graphics’
  520 |         lbm.graphics.visualization_modes = VIS_FLAG_LATTICE|VIS_FLAG_SURFACE;

Build finished with error(s).

 *  The terminal process terminated with exit code: -1. 
 *  Terminal will be reused by tasks, press any key to close it. 

For context, I am on a Linux machine under X11.

**Comment by ProjectPhysX** [comment]
Hi @andrewjosephlehmann,

uncomment [`INTERACTIVE_GRAPHICS`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/defines.hpp#L27) and the other settings instructed in the line where your `main_setup()` function begins. Then switch to [this line](https://github.com/ProjectPhysX/FluidX3D/blob/master/make.sh#L6) to compile with X11.

Kind regards,
Moritz
