### ISSUE TITLE
How to Increase VRAM Using Shared GPU Memory

### ISSUE THREAD

**Issue by wjsjtu123** [ProjectPhysX/FluidX3D#146]
My computer has 4GB of dedicated GPU memory and 15.8GB of shared GPU memory. when performing calculations, the grid resolution can only support a maximum of 4GB. how do I utilize my shared GPU memory so that I can increase my grid resolution?

**Comment by ProjectPhysX** [comment]
Hi @wjsjtu123,

the "shared GPU memory" is actually just half of the CPU memory. Even if it were possible, using this does not make sense - it would slow down the simulation by ~100x.

FluidX3D plows over the entire VRAM in every time step, so the faster the VRAM bandwidth the better. The CPU memory is way slower in bandwidth, and on top all the data would have to move over the (comparativley) super slow PCIe connection then.

In this case it's better to run FluidX3D entirely on the CPU. For this you need to install the [Intel OpenCL CPU Runtime](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-cpu-runtime-for-opencl-applications-with-sycl-support.html). Still way slower than GPU compute, but faster than copying everything over PCIe.

Kind regards,
Moritz

**Comment by wjsjtu123** [comment]
Once installed, how do I use it?

**Comment by ProjectPhysX** [comment]
--> https://github.com/ProjectPhysX/FluidX3D/issues/148#issuecomment-1959949707
