### ISSUE TITLE
make.sh fails on some systems due to nonstandard interpreter path

### ISSUE THREAD

**Issue by jansol** [ProjectPhysX/FluidX3D#147]
NixOS as one notable example.

The standard options are
* `/bin/sh` if very bare bones POSIX sh is enough
* `/usr/bin/env bash` if you need actual bash

**Comment by ProjectPhysX** [comment]
Does it work without the line `#!/bin/bash`?

**Comment by jansol** [comment]
Only if you pass it as an argument to the interpreter manually à la `bash ./make.sh`
