### ISSUE TITLE
Flow thorugh pipe

### ISSUE THREAD

**Issue by PP-JN-RL** [ProjectPhysX/FluidX3D#15]
First of all, thank you for your amazing work on this project, very much appriciated.

Is it possible to import a closed .stl geometry and define an inlet/outlet to simulate the flow through that geometry, like for example a pipe? If so, would you have main_setup() example that you could provide?

Thank you

**Comment by ProjectPhysX** [comment]
For such simple cases there is no need for an .stl file. You can directly insert geometries like cylinders/pipes/prisms/quboids... with the functions provided in [`src/shapes.hpp`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/shapes.hpp). There already is a flow through pipe setup in [`src/setup.cpp`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/setup.cpp) starting at line 48, used for error validation with the analytic solution. In this case, a short cylinder is inserted and there is no inlet/outlet, but periodic boundaries and the flow is driven with a volume force.

**Comment by PP-JN-RL** [comment]
Thank you for that, this should get me started. 
Is there a possiblity to use an .stl as the boundary and flow through it for more complex geometries?

**Comment by PP-JN-RL** [comment]
@ProjectPhysX Sorry to bother you again but would you have any advice on the above?
Effectively what I am trying to do is to flow inlet ports of an engine, which has quite complex geometry.
Looks a bit like this: 
![image](https://user-images.githubusercontent.com/52716446/196628338-fe1ee606-cbae-43c1-86ce-6d41d262af20.png)

**Comment by ProjectPhysX** [comment]
@PP-JN-RL in this case it''s best to make an .stl file for the geometry and another one for the inlet/outlet surfaces and then voxelize them with `TYPE_S`/`TYPE_E` respectively at the correct relative positions. If the inlet valve should be moving throughout the simulation, you'll need to re-voxelize the valve in between LBM time steps.
