### ISSUE TITLE
The model becomes rough

### ISSUE THREAD

**Issue by wjsjtu123** [ProjectPhysX/FluidX3D#151]
I imported the exact smooth stl model file, then during the simulation I found that the original smooth model became very rough, this should be related to the resolution of the simulation, I would like to ask if I increase the VRAM so that my model will become smooth.

**Comment by ProjectPhysX** [comment]
Hi @wjsjtu123,

the roughness is expected as the model is voxelized to the Cartesian LBM grid. This is related to the grid resolution, and the stairsteps will get smaller with increased VRAM size. See issue https://github.com/ProjectPhysX/FluidX3D/issues/149.

Kind regards,
Moritz
