### ISSUE TITLE
Little Bit irritating new version message with 1.4? Not 2.14?

### ISSUE THREAD

**Issue by stefano2734** [ProjectPhysX/FluidX3D#153]
Little Bit irritating new version 1.4? Not 2.14?

After Version 2.13 normal is next version 2.14 or 3.0 for major Version.

**Comment by ProjectPhysX** [comment]
Hi @stefano2734,

please ignore this, v2.13 is still the latest version, and v1.4 is very old.
I realized today that I had misspelled the v1.4 tag to "v1,4", and I was correcting the typo in this tag today.

Kind regards,
Moritz

PS: Update v2.14 is coming soon!
