### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by PavelBlend** [ProjectPhysX/FluidX3D#154]
Hello @ProjectPhysX .

I have a question:

Is the water simulation (https://youtu.be/oC6U1M0Fsug) slower than the airflow simulation (https://youtu.be/clAqgNtySow)? Is it possible to create a water simulation using 2 TB of video memory that will contain 40 billion voxels? If so, how much slower will it be than creating airflow?

I'd like to see a "cascade" simulation like the one in this video https://youtu.be/EI8X57M_rt8 that has 40 billion voxels. In the video, the fluid has a resolution of 512 x 385 x 256, which is 50 462 720 voxels. If there are 40 billion voxels, then the resolution will be 4740 x 3556 x 2370.

**Comment by ProjectPhysX** [comment]
Hi @PavelBlend,

free surface (water) simulations are typically a bit faster than airflow simulations / [benchmark values](https://github.com/ProjectPhysX/FluidX3D?tab=readme-ov-file#single-gpucpu-benchmarks), as not the entire box is filled with water and the air part is not computed at all then. Free surface simulations (enable [`SURFACE`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/defines.hpp#L22) extension) need (55+12) Byte/cell in memory (the 12 Byte/cell extra are for the extension), so 2TB VRAM will fit ~31 Billion cells. At only 50M cell resolution like in this blender video, such a cascade simulation should run close to real time on an RTX 3090. Should be fun!

Kind regards,
Moritz
