### ISSUE TITLE
Turbulence details are not displayed clearly after enabling FORCE_FIELD

### ISSUE THREAD

**Issue by wjsjtu123** [ProjectPhysX/FluidX3D#155]
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/0aa25b05-9421-48a9-93e6-4c390e7df5bb)
This is the Q cloud obtained by calculating the lift coefficient with FORCE_FIELD enabled, and I'm wondering why it turns black and doesn't show more turbulence detail very well. What should I do to get more turbulence details like in this picture below。
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/fcfd01d7-0d96-4ec4-aeab-15ecf6c429b1)

**Comment by wjsjtu123** [comment]
And open the visualization interface in linux system, this visualization interface sometimes does not work and become very laggy.

**Comment by ProjectPhysX** [comment]
Hi @wjsjtu123,

`FORCE_FIELD` in itself only adds an additional force vector `lbm.F` to each cell, and allows calculation of boundary forces. To actually compute boundary forces for rendering, call `lbm.calculate_force_on_boundaries();` in a loop with `lbm.run(1u);`, like this:
```c
while(true) { // main simulation loop
	lbm.run(1u);
	lbm.calculate_force_on_boundaries();
}
```

The reason to not include `calculate_force_on_boundaries()` in the `run()` function is that it needs extra compute time, and in many setups updating the boundary forces may only be required before exporting forces, or before rendering video frames, not in every single time step.

Kind regards,
Moritz
