### ISSUE TITLE
FR: option to flip the left/right of stereoscopic rendering

### ISSUE THREAD

**Issue by chconnor** [ProjectPhysX/FluidX3D#157]
Hi -- Typing "V" enables the stereoscopic rendering, which (for good reasons, I'm sure) orients the left/right opposite of how one would naturally view stereo images by crossing their eyes.

Meaning, if you cross your eyes to view the images overlaid with each other, they are backwards and the 3D effect doesn't work.

I know this isn't the intended use of the V feature, but it would be nice if there was an option to flip the left/right orientation so we could do 3D viewing without VR goggles, etc. :-)

Thanks!

**Comment by ProjectPhysX** [comment]
Hi @chconnor,

I won't put this into the main repo as it's quite an unusual feature, but you can flip left/right images by removing the limit of the `eye_distance` variable, changing [`src/graphics.hpp` line 311](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/graphics.hpp#L311) from
```c
eye_distance = fmax(eye_distance-0.2f, 0.0f);
```
to
```c
eye_distance -= 0.2f;
```
and then in the running application holding key <kbd>N</kbd> until you reach the desired inverse 3D effect. The help menu with key <kbd>H</kbd>will always show you the current value of `eye_distance`, and you can set its default value [here](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/graphics.hpp#L35).

Kind regards,
Moritz

**Comment by chconnor** [comment]
Great, thanks for the tips!
