### ISSUE TITLE
Minor issue: key shortcuts are described wrong on help screen

### ISSUE THREAD

**Issue by chconnor** [ProjectPhysX/FluidX3D#158]
Hi -- the help screen describes "Y/X ( xx): adjust camera field of view" when I believe the actual keys are Z/X.

It also says "Z: (      velocity u        ): toggle field visualization mode" when I believe the actual key is Y.

Thanks!

**Comment by ProjectPhysX** [comment]
Hi @chconnor,

on German keyboard layout, keys <kbd>Y</kbd> and <kbd>Z</kbd> are switched compared to US keyboard layout. I assume you're using Linux, where I did the [map from key codes to keys](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/graphics.cpp#L575) manually. I'll search a way to do this automatically for different keyboard layouts.

Kind regards,
Moritz

**Comment by chconnor** [comment]
Yes, I'm on Linux (in the US).

Thanks!

**Comment by ProjectPhysX** [comment]
Hi @chconnor,

I have [fixed](https://github.com/ProjectPhysX/FluidX3D/commit/3a5a15e499189028287dfee199e5f570bd1df3a4) it (I hope). Please check with your keyboard and let me know in case Y and Z are still incorrect.

Kind regards,
Moritz

**Comment by chconnor** [comment]
Looks perfect now, thanks!
