### ISSUE TITLE
Aircraft vertical tail voxelization problem

### ISSUE THREAD

**Issue by wjsjtu123** [ProjectPhysX/FluidX3D#160]
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/a31d2780-84d2-4ac3-907a-c3f87beaca92)
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/71e1d6a3-b72d-4397-95ca-9e274d1d9bb9)
When I voxelize no matter how much resolution I use, the plane's vertical tail always fails to show up in the GPU, whereas I don't have this problem with my horizontal tail. I suspect that my vertical tail thickness is too thin, but my horizontal tail thickness is also very thin. How do I fix this problem, thanks!

**Comment by ProjectPhysX** [comment]
Hi @wjsjtu123,

there is two possible error sources:
- If the mesh is not watertight (there is holes between triangle edges, or triangles are overlapping), voxelization will fail.
- If the wing is thinner than 1 grid cell, it may not get voxelized at all when it's located in between grid layers and no cell center points are inside the wing volume.

You can try to fix (or differently discretize) the mesh with for example Windows 3D Builder. 3D Builder has a function to fix meshes and to coarsen them. Use binary stl export then. Hope this helps!

Kind regards,
Moritz
