### ISSUE TITLE
What the color rendering represents

### ISSUE THREAD

**Issue by wjsjtu123** [ProjectPhysX/FluidX3D#169]
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/3c5ceca9-2e15-4482-a057-f79ce949651c)
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/695bb1c2-5c14-45a6-bc5e-9302e06d73ea)
I would like to know what this this color rendering on the ground represents? I have wall boundary conditions turned on, as well as force field.

**Comment by ProjectPhysX** [comment]
This is the pressure on boundaries as computed in last `lbm.calculate_force_on_boundaries()` call.

**Comment by wjsjtu123** [comment]
So what is the correlation between the amount of pressure and the depth of the colour, for example is the yellow part of the picture more pressure than the blue part?

**Comment by ProjectPhysX** [comment]
Yes yellow is positive pressure on the walls, blue is negative pressure. I don't yet have a color bar for this but it's similar to density color scale.
