### ISSUE TITLE
paraview extracts lift, drag, and pressure clouds.

### ISSUE THREAD

**Issue by wjsjtu123** [ProjectPhysX/FluidX3D#173]
I extracted the rho and u data in vtk format with two commands lbm.rho.write_device_to_vtk(); and lbm.u.write_device_to_vtk();. In paraview, I want to get a visual cloud of pressure, lift and drag from these two data, how do I do it.
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/69c2c4d5-3f0c-4d25-80a9-ef051a0834b6)

**Comment by ProjectPhysX** [comment]
Hi @wjsjtu123,

- pressure is proportional to density, in LBM units: `Δp = (rho-rho0)*c^2 = (rho-1)/3`
- you can get the pressure delta in SI units with
  ```c
  const float si_delta_p_n = units.si_p((lbm.rho[n]-1.0f)/3.0f);
  ```
- there is no way yet to export pressure directly to `.vtk`, you can only export density and convert to pressure manually
- to get the forces, you first have to export the force field to `.vtk`:
  ```c
  lbm.calculate_force_on_boundaries();
  lbm.F.write_device_to_vtk();
  ```

Kind regards,
Moritz
