### ISSUE TITLE
Code fails in interactive mode sending "xcb_xlib_threads_sequence_lost".

### ISSUE THREAD

**Issue by RusGB** [ProjectPhysX/FluidX3D#174]
Version 2.15 fails in Ubuntu 22.04.4 while testing Lid cavity problem in interactive mode.
-------------------
The following error is dumped:

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
FluidX3D: ../../src/xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
./make.sh: line 33: 21612 Aborted                 (core dumped) bin/FluidX3D "$@"

The **solution** was to include a call for _XInitThreads();_ in _graphics.cpp_  in main() just before "_x11_display = XOpenDisplay(0);_" (line 686).
This seems to work, yet have not tested with other problems.

**Comment by ProjectPhysX** [comment]
Hi @RusGB,

thanks for reporting this bug! I've [fixed](https://github.com/ProjectPhysX/FluidX3D/commit/fc85c1b49a50aaf4a67c21f415e39fc60494dede) it!

Kind regards,
Moritz
