### ISSUE TITLE
Calculation of liquid that does not fit in memory

### ISSUE THREAD

**Issue by PavelBlend** [ProjectPhysX/FluidX3D#177]
@ProjectPhysX Hello.

Your program runs on multiple GPUs. The calculation results from all GPUs are combined. Can you add the ability to compute on one CPU/GPU, but have two or more domains? To be able to carry out calculations for only one domain. Then the program must combine all calculations.

If this feature is implemented, it will be possible to run the simulation on 128 GB or more of video memory on a single 16 GB GPU. Each domain will be calculated sequentially, one after the other. All intermediate results will be saved to the SSD.

**Comment by ProjectPhysX** [comment]
Hi @PavelBlend,

although this is possible in theory, it would be abysmally slow in practice. Spilling/switching domains to RAM or even SSDs is 500-2000x slower. One minute compute would turn into a day. With large simulations in the billions of cells, runtime would blow up from hours to months. This is not a feasible solution, so I'm not planning to implement this.

The problems is that the data has to be _moved_ through bottlenecks of very slow bandwidth. With only 1 domain on the GPU, you get ~200-2000 GB/s in VRAM bandwidth (depending on GPU model); data only moves between VRAM and GPU die. Swapping domains to CPU RAM would mean that the full 16GB data has to go through PCIe in every time step at 8-16 GB/s, multiple times (8x for 128GB split into 16GB domains). Swapping to SSD means 0.5-7 GB/s, even slower.

There are 3 more viable alternatives:
- Put 128GB CPU RAM into your system and [run FluidX3D on the CPU](https://github.com/ProjectPhysX/FluidX3D/issues/148#issuecomment-1959949707). CPU RAM has a bandwidth of 50-200GB/s, slower than GPUs but not as bad as swapping data over the PCIe bus. Some old server CPUs support 4- or 8-channel RAM, for much better bandwidth.
- Get an old X99 or Threadripper mainboard on eBay, along with 4x Tesla P40 24GB GPUs for ~$175 each - 96GB VRAM for cheap. @SLGY has a [similar system with 3x K80 dual-GPUs](https://youtu.be/TS5cvCOmQDw?t=40s) for 72GB VRAM.
- Rent some cloud GPU server.

Kind regards,
Moritz
