### ISSUE TITLE
LBM has no member "graphics"

### ISSUE THREAD

**Issue by LiPo127** [ProjectPhysX/FluidX3D#179]
every time I try to compile with any example it gives me this error.

**Comment by ProjectPhysX** [comment]
Hi @LiPo127,

go to [`defines.hpp`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/defines.hpp), comment out
```c
//#define BENCHMARK
```
and uncomment
```c
#define INTERACTIVE_GRAPHICS
```
Then recompile. This enables the graphics functionality of the LBM class.

Kind regards,
Moritz
