### ISSUE TITLE
Thermal flux boundary condition

### ISSUE THREAD

**Issue by rodionstepanov** [ProjectPhysX/FluidX3D#18]
How difficult is fixed temperature gradient to implement?

**Comment by ProjectPhysX** [comment]
Easy. Enable the TEMPERATURE extension in src/defines.hpp, set the temperature boundary flag `lbm.flags[n] = TYPE_T;` and fix the temperature value at flagged points with `lbm-T[n] = 1.0f+your_deltaT;`. Note that temperatures are in LBM units and should be centered around `1.0f`. See the sample setups [here](https://github.com/ProjectPhysX/FluidX3D/blob/4f3c5d447aa8236023628dfa26006142bdf3fd38/src/setup.cpp#L844).

**Comment by rodionstepanov** [comment]
I've tried this 
		if(z==1u) {
			lbm.T[n] = 2.0f;
			lbm.flags[n] = TYPE_T;
		} else if(z==Nz-2u) {
			lbm.T[n] = 1.0f - 1.0f/(float)Nz;
			lbm.flags[n] = TYPE_T;
		}
expecting to get a stable state with fix temperature T=2 at bottom and T=1 at the top since total drop is -1. However it is not working. Why?

**Comment by rodionstepanov** [comment]
I don't understand why `lbm.T[n] = 1.0f+your_deltaT;` would correspond  the Neumann (or second-type) boundary condition 
I've tried this
if(z==1u) {
lbm.T[n] = 2.0f;
lbm.flags[n] = TYPE_T;
} else if(z==Nz-2u) {
lbm.T[n] = 1.0f + 1.0f/(float)Nz;
lbm.flags[n] = TYPE_T;
}
expecting to get a stable state with fix temperature T=2 at bottom and T=3 at the top since total drop is -1. However it is not working.
