### ISSUE TITLE
C2084 function 'int main(int,char* {})' already has a body............in file graphics. cpp

### ISSUE THREAD

**Issue by RayLin0601** [ProjectPhysX/FluidX3D#180]
error 1 
showed up in line 512 int main(int argc, char* argv[]) { 
and line                772 int main(int argc, char* argv[]) {

error 2
 469 void update_frame(const double frametime) {
744 void update_frame(const double frametime) {

**Comment by ProjectPhysX** [comment]
Hi @RayLin0601,

can you please share the contents of your `src/defines.hpp` file?

Kind regards,
Moritz

**Comment by RayLin0601** [comment]
[defines.txt](https://github.com/ProjectPhysX/FluidX3D/files/15285482/defines.txt)

**Comment by RayLin0601** [comment]
ive look through it but looks fine

**Comment by ProjectPhysX** [comment]
2 problems in there:
- comment out `D2Q9`, `D3Q15` and `D3Q27`
- comment one of the 2: `INTERACTIVE_GRAPHICS` or  `INTERACTIVE_GRAPHICS_ASCII` --> having both `INTERACTIVE_GRAPHICS` and `INTERACTIVE_GRAPHICS_ASCII` active at the same time causes the compiler error with the 2 active main functions

Kind regards,
Moritz
