### ISSUE TITLE
D3Q15 Dam Breaking Expanding Water

### ISSUE THREAD

**Issue by Meerkov** [ProjectPhysX/FluidX3D#182]
Using D3Q15 and the breaking dam, the water upon reaching the far side of the box will inflate until it fills the entire box. Right around step 1700 it triggers the error. 
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/96b3dfd2-fd2c-4b47-8cec-b9828c4f74f5)
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/4ec89c0b-9c95-49a6-91cb-64ba2235290d)

Given that it seems to only happen after touching the right most wall, I wonder if it's not due to a property of D3Q15, but actually due to a bug, maybe on how it interacts on that wall

There seem to be other D3Q15 errors as well on other simulations.

**Comment by ProjectPhysX** [comment]
Hi @Meerkov,

this is simulation instability. D3Q15 is less accurate and less stable than D3Q19, yet has reduced memory footprint. This is a known phenomenon, and the reason why D3Q19 has been established the default for LBM.

Kind regards,
Moritz

**Comment by Meerkov** [comment]
Thanks for the reply. That makes sense.

My understanding is that instability is caused by a cell going below approximately 0.001 in density (based on my own implementation on D2Q9). 

I'm curious whether it's possible to recover/correct the instability by adding a small amount of fluid to such cells. I haven't seen that recover mechanism discussed, but I'm still new to LBM. I imagine it would introduce an overhead in order to check every cell for the instability condition.

Do you know whether such a correction mechanism has been explored, or whether it would cause more problems than it solves?

**Comment by ProjectPhysX** [comment]
Hi @Meerkov,

yes there is mechanisms to improve stability by trading off accuracy when edge cases are hit, such as clamping values. I'm already [clamping velocity](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/kernel.cpp#L1608) to the lattice speed of sound. Similar clamping for density could also be applied. There is no runtime overhead for clamping as it's still memory-bound.
Another method is the subgrid models for simulations at very high Reynolds numbers - in FluidX3D that's [Smagorinsky-Lilly subgrid model](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/kernel.cpp#L1649) - these locally increase viscosity to an effective eddy viscosity in grid cells where the shear rate is high. Coincidentally, cells with high shear rate and low viscosity are the source of instability, and increasing viscosity there improves stability a lot.

Kind regards,
Moritz
