### ISSUE TITLE
Visualizing rho and u in Paraview

### ISSUE THREAD

**Issue by aiotko** [ProjectPhysX/FluidX3D#186]
Hi,

I just wanted to start by saying thank you so much for sharing your project - it's really impressive!

Sorry for the beginner's question, could you please advise the way how to visualize rho and u in Paraview to get the visual picture like in Interactive Graphics mode?

I've tried using _Contour_ for rho and _Glyph_ for u, but Glyph crashed Paraview even with 80 Gb of RAM and Contour didn't look like the expectation )

**Comment by ProjectPhysX** [comment]
Hi @aiotko,

ParaView offers 2 `Representation` options for visualizing volumetric data:
- `Slice`: for velocity you can also select between Magnitude or X/Y/Z components
- `Volume`: for density you can also use `Shade`+`Show Isosurfaces`

Unfortunately, ParaView can't do Q-criterion isosurface like my built-in rendering engine.

Kind regards,
Moritz

**Comment by AlexandrIotko3Shape** [comment]
Thank you for your explanation, @ProjectPhysX,

I'm just looking for a way to visualize Q-criterion isosurface from VTK output by pyvista or vtk in Python or C++ to have a view like in your engine since it's pretty useful.

Maybe you have an example of how to do it?

**Comment by aiotko** [comment]
Thank you for your explanation, @ProjectPhysX,

I'm just looking for a way to visualize Q-criterion isosurface from VTK output by pyvista or vtk in Python or C++ to have a view like in your engine since it's pretty useful.

Maybe you have an example of how to do it?

**Comment by ProjectPhysX** [comment]
ParaView can't do Q-criterion isosurfaces out-of-the-box unfortunately from 3-component vector data. [This](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/kernel.cpp#L2778) is how it's implemented in FluidX3D:
- for each of 8 cells in a cube, [calculate the Q-value from a 6-point stencil](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/kernel.cpp#L1028)
- calculate vertex positions of up to 5 triangles with [marching-cubes ](marching_cubes)
- color triangles based on interpolated velocity/color/temperature
- rasterize triangles

You'd have to copy the part to calculate the Q-value for each cell to your C++ setup and run it on the entire grid on CPU; you can temporarily store Q-values in the `lbm.rho` data field. Then export it to `.vtk` and let paraview draw the isosurfaces - without coloring though.
