### ISSUE TITLE
No progress - stuck at Step 0 (benchmark works)

### ISSUE THREAD

**Issue by EmilEmilchen** [ProjectPhysX/FluidX3D#188]
First I want to apologize in advance in case I've missed something obvious, it's safe to say that I don't have a lot of experience with either C++ or more advanced CFD software.
I followed the documentation but when trying to run the first example I ran into some kind of problem: After waiting around 10 minutes the console output doesn't change, neither does the GUI
Terminal:
![Screenshot_20240530_175243](https://github.com/ProjectPhysX/FluidX3D/assets/70268797/4f8d0e0a-7305-488c-8e55-7065a10fd6b9)
GUI:
![Screenshot_20240530_175505](https://github.com/ProjectPhysX/FluidX3D/assets/70268797/71a9628e-4063-49dd-8ba1-3ce8e57bed2b)
I've also tried things like the 2D example and the Benchmark: 
![Screenshot_20240530_175703](https://github.com/ProjectPhysX/FluidX3D/assets/70268797/def8128a-8ec8-4a6f-867c-3365bcbae400)
(Benchmark Output, seems to be working just fine, doesn't stop automatically, needs to be stopped manually)

When running the 3rd example without Interactive Graphics the behavior differs and at least something happens:
![Screenshot_20240530_180109](https://github.com/ProjectPhysX/FluidX3D/assets/70268797/acb252a2-5167-469e-bbc1-c66415a89431)
To be completely honest, I'm not entirely sure if the program is supposed to terminate automatically but I'd assume so.

During the Benchmark my GPU is utilized just like I assume it's supposed to be:
![Screenshot_20240530_180915](https://github.com/ProjectPhysX/FluidX3D/assets/70268797/be3c3316-3686-440f-ade5-7f2788d5e9b0)

When running any of the other examples (the ones I mentioned in this post anyway, I didn't try every single one) however, my GPU utilization doesn't change in any meaningful way whatsoever:
![Screenshot_20240530_181231](https://github.com/ProjectPhysX/FluidX3D/assets/70268797/6441b2ee-b17b-4b63-9b7f-995048e8e2e0)
and:
![Screenshot_20240530_181353](https://github.com/ProjectPhysX/FluidX3D/assets/70268797/85e60ea0-d688-4d05-8e2e-d49609e52524)

I couldn't find mention of any similar kind of problem online.

I'd really appreciate some help, thanks in advance!

Edit: In the next few days I'll also try running this on my home server in a debian proxmox machine with a 3060 Ti and see if it works there but even if it does I'd still like to be able to use my Laptop as well.

**Comment by ProjectPhysX** [comment]
Hi @EmilEmilchen,

with interactive graphics, the simulation starts up in paused state, to allow inspecting initial conditions. In the graphics window, press key <kbd>P</kbd> to start (and later pause/continue) the simulation.
Have fun!

Kind regards,
Moritz

**Comment by EmilEmilchen** [comment]
Thank you a lot for the quick help, don't know why I didn't try this, anyway, it works like a charm now!
Love the software, I'm used to closed source stuff and this is open source and better then what I've been using!
