### ISSUE TITLE
cannot find file "FluidX3D.exe"

### ISSUE THREAD

**Issue by SupaTroopa2008** [ProjectPhysX/FluidX3D#189]
I downloaded the program and am setting it up on an unmodified version of Windows 11, but when I tried to run the first setup file Visual Studio first told me that there were build errors, and offered to run an earlier version, and when continuing, it throws an error and states that it cannot find the file. I have looked over the steps several times but it hasn't fixed it. any tips?

![Screenshot 2024-06-01 150508](https://github.com/ProjectPhysX/FluidX3D/assets/170808456/59ef6644-6bc3-488a-b9c0-2f29f06d6229)

**Comment by gitcnd** [comment]
You need to uncomment whatever demo you want to run in the C++ code (and probably get the files needed for it from thingiverse)... and you will probably have needed to install the correct versions of the Visual Studio tools too (pay close attention to the FluidX3d instructions).

You need to paste your build errors here - "file not found" isn't a useful error.

**Comment by ProjectPhysX** [comment]
Hi @SupaTroopa2008,

please precisely follow the [instructions](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#3-go-through-sample-setups). Check the build errors - they will tell you what's wrong. If you need help with the build errors, please copy/paste them here in the replies, so I can help you.

Kind regards,
Moritz
