### ISSUE TITLE
Graphics output not responding respectively throwing error

### ISSUE THREAD

**Issue by gittigittibangbang** [ProjectPhysX/FluidX3D#19]
Hello, I tried running some models with graphics output, for example the 3D Taylor-Green vortices model. With all the settings at default (#define BENCHMARK commented out), I struggle to receive a graphics output. When using WINDOWS_GRAPHICS, the setup does not compile with the output below. When trying to use CONSOLE_GRAPHICS, the console seems to prepare the space for the output with the pixel counter on the bottom right, but the space stays black. Defining GRAPHICS works, but where is the file output to? In addition, where can the time step or output time step be altered? I use Windows 10 and WSL if it's of importance.

WINDOWS_GRAPHICS output:
`$ ./make.sh
In file included from ./src/opencl.hpp:14,
                 from ./src/lbm.hpp:4,
                 from ./src/info.cpp:2:
./src/OpenCL/include/CL/cl.hpp:5085:28: warning: ignoring attributes on template argument 'cl_int' {aka 'int'} [-Wignored-attributes]
 5085 |         VECTOR_CLASS<cl_int>* binaryStatus = NULL,
      |                            ^
In file included from ./src/opencl.hpp:14,
                 from ./src/lbm.hpp:4,
                 from ./src/lbm.cpp:1:
./src/OpenCL/include/CL/cl.hpp:5085:28: warning: ignoring attributes on template argument 'cl_int' {aka 'int'} [-Wignored-attributes]
 5085 |         VECTOR_CLASS<cl_int>* binaryStatus = NULL,
      |                            ^
In file included from ./src/opencl.hpp:14,
                 from ./src/lbm.hpp:4,
                 from ./src/main.cpp:2:
./src/OpenCL/include/CL/cl.hpp:5085:28: warning: ignoring attributes on template argument 'cl_int' {aka 'int'} [-Wignored-attributes]
 5085 |         VECTOR_CLASS<cl_int>* binaryStatus = NULL,
      |                            ^
In file included from ./src/opencl.hpp:14,
                 from ./src/lbm.hpp:4,
                 from ./src/setup.hpp:4,
                 from ./src/setup.cpp:1:
./src/OpenCL/include/CL/cl.hpp:5085:28: warning: ignoring attributes on template argument 'cl_int' {aka 'int'} [-Wignored-attributes]
 5085 |         VECTOR_CLASS<cl_int>* binaryStatus = NULL,
      |                            ^
In file included from ./src/opencl.hpp:14,
                 from ./src/lbm.hpp:4,
                 from ./src/shapes.cpp:2:
./src/OpenCL/include/CL/cl.hpp:5085:28: warning: ignoring attributes on template argument 'cl_int' {aka 'int'} [-Wignored-attributes]
 5085 |         VECTOR_CLASS<cl_int>* binaryStatus = NULL,
      |                            ^
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1ac9): undefined reference to `__imp_SetBitmapBits'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1b2a): undefined reference to `__imp_SetTextColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1b68): undefined reference to `__imp_TextOutA'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1bd8): undefined reference to `__imp_TextOutA'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1c45): undefined reference to `__imp_TextOutA'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1cae): undefined reference to `__imp_SetPixel'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1d20): undefined reference to `__imp_SetPixel'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1d33): undefined reference to `__imp_GetStockObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1d49): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1d88): undefined reference to `__imp_SetDCPenColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1df1): undefined reference to `__imp_Ellipse'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1e2e): undefined reference to `__imp_Ellipse'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1e3c): undefined reference to `__imp_GetStockObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1e52): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1eaf): undefined reference to `__imp_SetDCPenColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1ed1): undefined reference to `__imp_MoveToEx'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1eed): undefined reference to `__imp_LineTo'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1f6e): undefined reference to `__imp_SetDCPenColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1fad): undefined reference to `__imp_SetDCBrushColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x1fca): undefined reference to `__imp_Polygon'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x2027): undefined reference to `__imp_SetDCPenColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x2066): undefined reference to `__imp_SetDCBrushColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x208b): undefined reference to `__imp_Rectangle'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x2189): undefined reference to `__imp_SetDCPenColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x21c8): undefined reference to `__imp_SetDCBrushColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x21e5): undefined reference to `__imp_Polygon'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x2259): undefined reference to `__imp_SetTextColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x2297): undefined reference to `__imp_TextOutA'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x377d): undefined reference to `__imp_CreateRectRgn'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x3793): undefined reference to `__imp_SelectClipRgn'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x3b3e): undefined reference to `__imp_BitBlt'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x3b4c): undefined reference to `__imp_GetStockObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x3b62): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x3b74): undefined reference to `__imp_GetStockObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x3b8a): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x3bc3): undefined reference to `__imp_Rectangle'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x3bda): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x3bf1): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x4038): undefined reference to `__imp_GetStockObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x4278): undefined reference to `__imp_CreateCompatibleBitmap'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x4292): undefined reference to `__imp_CreateCompatibleDC'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x42b3): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x42cd): undefined reference to `__imp_DeleteObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x42db): undefined reference to `__imp_GetStockObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x42f1): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x42ff): undefined reference to `__imp_GetStockObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x4315): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x432d): undefined reference to `__imp_SetDCPenColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x4345): undefined reference to `__imp_SetDCBrushColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x435d): undefined reference to `__imp_SetTextAlign'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x4375): undefined reference to `__imp_SetBkMode'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x438d): undefined reference to `__imp_SetPolyFillMode'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x4400): undefined reference to `__imp_CreateFontA'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text+0x4421): undefined reference to `__imp_SelectObject'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text$_ZNK8Triangle4drawEv[_ZNK8Triangle4drawEv]+0x46): undefined reference to `__imp_SetDCPenColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text$_ZNK8Triangle4drawEv[_ZNK8Triangle4drawEv]+0x86): undefined reference to `__imp_SetDCBrushColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text$_ZNK8Triangle4drawEv[_ZNK8Triangle4drawEv]+0xa7): undefined reference to `__imp_Polygon'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text$_ZNK10Quadrangle4drawEv[_ZNK10Quadrangle4drawEv]+0x46): undefined reference to `__imp_SetDCPenColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text$_ZNK10Quadrangle4drawEv[_ZNK10Quadrangle4drawEv]+0x86): undefined reference to `__imp_SetDCBrushColor'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Thierry\AppData\Local\Temp\ccmwGO2p.o:graphics.cpp:(.text$_ZNK10Quadrangle4drawEv[_ZNK10Quadrangle4drawEv]+0xa7): undefined reference to `__imp_Polygon'
collect2.exe: error: ld returned 1 exit status
./make.sh: line 7: ./bin/FluidX3D.exe: No such file or directory`

**Comment by ProjectPhysX** [comment]
With the `WINDOWS_GAPHICS` option you'll have to compile in Windows directly, for example with the MSVC compiler in Visual Studio Community. Compiling that in WSL will not work, as that's a linux environment.

The `CONSOLE_GRAPHICS` option works in both Windows and Linux/WSL, provided your GPU appears as OpenCL device in WSL. Once the ASCII graphics window and pixel counter appears, the simulation is paused and by default grid flags are visualized. In the 3D Taylor-Green setup there is no solid geometry, so no flags are visualized and the window initially looks black. Press key 4 to enable Q-criterion isosurface visualization, or the other visualization modes with keyx 2 or 3, then you should see something. Press P to start/pause the simulation. You can rotate the camera with W/A/S/D.

**Comment by gittigittibangbang** [comment]
Thank you, I got it working with the GRAPHICS option, and I'll try getting the WINDOWS_GRAPHICS option to work, too. Pictures of the cylinder model look great, but the ones from the F1 car, Concorde or 747 model tend to fill up with isosurfaces completely, even when using varying values of the Q-criterion. Do you have a recommendation for that? By the way, is it possible to create cutting planes and legends?

And again, thanks for creating and publishing your solver, it could really be the kick in the ass for some bigger solver developers to modernize their codes! It's really great work :)

**Comment by ProjectPhysX** [comment]
What you see is the simulation blowing up at large Reynolds numbers. For these you need to enable SUBGRID in src/defines.hpp!

**Comment by gittigittibangbang** [comment]
Ah, that makes sense, thank you.

Another quick question: I compiled the benchmark files on my home PC to run them on a workstation, which works fine. However, using the same workflow to compile the exe (using MinGW bash environment to use ./make.sh) on the workstation, the solver does not run stating that no OpenCL devices are available. Since the files created on my personal PC worked without a problem on the workstation using either the GPU or CPU, this seems odd. Do you happen to know what the issue might be? The GPU drivers are installed, of course.
