### ISSUE TITLE
Applying a force during simulation to simulate main line water pressure

### ISSUE THREAD

**Issue by mikehnta00** [ProjectPhysX/FluidX3D#197]
Starting with the "periodic faucet mass conservation test;" I am trying to add a force to the water as it comes out of the z = Nz plane. 

Is there a feature or an easy way to add a layer of cells that applies a certain force to the water during simulation? 

It seems when you use the SURFACE define  it enables UPDATE_FIELDS so rho, u, T are updated in every LBM step.

This might be overriding my attempt, or more likely, I'm not even be accessing the correct data with my additional code in setup.cpp
Here is my attempt to add a force to the water:
`
	}); // ############################# run simulation, export images and data ###################################
	lbm.graphics.visualization_modes = VIS_FLAG_LATTICE|VIS_PHI_RASTERIZE;
	lbm.run();
	const uint D = max(Nx, Nz), R = D / 6;
	const ulong n = lbm.get_N();
	uint x = 0u, y = 0u, z = 0u; 
	lbm.coordinates(n, x, y, z);
	while (true) {
		//if inside the force circle,
		for (int i= 0; i< n; i++) { 
			if (y == Nx/2u+2u*R+5u && sq(x-Nx/2u)+sq(z-(Nz-R))>sq(R)) lbm.u.y[n] = lbm.u.y[n]+0.9f; //  add force to the water
			};
	}
`

**Comment by mikehnta00** [comment]
Actually I see now that using a TYPE_E boundary in the initialization does exactly this.

I just added something like this to the top source:
		if (z==Nz-1u && sq(x-Nx/2u)+sq(y-Ny/2u)>sq(R)) {
			lbm.flags[n] = TYPE_E; // z non periodic, build top source
			lbm.u.z[n] = 0.75f; // z non periodic, build top force addition
		}
Hope this helps someone!

**Comment by ProjectPhysX** [comment]
Hi @mikehnta00,

there is a very convenient and also physically correct way in place to do this:
- enable both `VOLUME_FORCE` and `FORCE_FIELD` extensions in `src/defines.hpp`
- then in the `main_setup()` function as part of the initial conditions, you can set a volume force `lbm.F.z[n]` (x or y components analogous) for each cell `n` individually
- this additional volume force you've set in your one layer of cells will be applied throughout the simulation, additive to the global volume force

No need to pull out and modify the velocity. The `TYPE_E` boundaries are only for fixed-velocity boundary conditions.

Kind regards,
Moritz
