### ISSUE TITLE
NIT: No Volume Force in 2D Taylor Vortex

### ISSUE THREAD

**Issue by Meerkov** [ProjectPhysX/FluidX3D#198]
https://github.com/ProjectPhysX/FluidX3D/blob/ad1418020b4f188d47d3b60afd684665b7ccb51b/src/setup.cpp#L41

The extension VOLUME_FORCE is not required. But the comment says it uses volume force. Applies to multiple examples.

**Comment by ProjectPhysX** [comment]
Hi @Meerkov,

therse lines are only meant as section headers.
Technically, the LBM constructor always sets the volume force here, in this case only with default parameters to 0 :)

Kind regards,
Moritz
