### ISSUE TITLE
Unnecessary neighbor calculations

### ISSUE THREAD

**Issue by Meerkov** [ProjectPhysX/FluidX3D#199]
https://github.com/ProjectPhysX/FluidX3D/blob/4258d2e5b69ce5966dea1237aeec4bb7cee69f46/src/kernel.cpp#L993
```cpp
	j[ 1] = xp+y0+z0; j[ 2] = xm+y0+z0; // +00 -00
	j[ 3] = x0+yp+z0; j[ 4] = x0+ym+z0; // 0+0 0-0
	j[ 5] = x0+y0+zp; j[ 6] = x0+y0+zm; // 00+ 00-
	j[ 7] = xp+yp+z0; j[ 8] = xm+ym+z0; // ++0 --0
	j[ 9] = xp+y0+zp; j[10] = xm+y0+zm; // +0+ -0-
	j[11] = x0+yp+zp; j[12] = x0+ym+zm; // 0++ 0--
	j[13] = xp+ym+z0; j[14] = xm+yp+z0; // +-0 -+0
	j[15] = xp+y0+zm; j[16] = xm+y0+zp; // +0- -0+
	j[17] = x0+yp+zm; j[18] = x0+ym+zp; // 0+- 0-+
	j[19] = xp+yp+zp; j[20] = xm+ym+zm; // +++ ---
	j[21] = xp+yp+zm; j[22] = xm+ym+zp; // ++- --+
	j[23] = xp+ym+zp; j[24] = xm+yp+zm; // +-+ -+-
	j[25] = xm+yp+zp; j[26] = xp+ym+zm; // -++ +--
```

`j[even]` are only used when calclating Surface.
`const uchar flagsji_su = flags[j[i]]&TYPE_SU; // extract SURFACE flags`
when resetting velocity of nodes with only solid neighbors, which seems rare or even unnecessary because a node with only solid neighbors is likely to be solid itself, which zeros the velocity anyway.
`		for(uint i=1u; i<def_velocity_set; i++) TYPE_ONLY_S = TYPE_ONLY_S&&(flagsj[i]&TYPE_BO)==TYPE_S;`

Only half of these values are ever used in the esoteric pull algorithm. Only the odd indexes are used, while the even ones are never used.

Given the purpose seems to be to to ensure high degree of optimization, It seems like these can either be removed entirely, or guarded by a SURFACE or MOVING BOUNDARIES requirement.

**Comment by ProjectPhysX** [comment]
Hi @Meerkov,

good find!
Here the compiler is smart enough to detect and remove the unused variables. PTX assembly is identical with `j[even]` removed.
Since the `neighbors()` function is called in some other places where `j[even]` are needed, I'll leave it as-is, to not overcomplicate with even more macto switches.

Kind regards,
Moritz

**Comment by Meerkov** [comment]
That makes sense, the macro switches get pretty confusing.

I feel like there is probably an arrangement of the memory that would make it more optimal for those cases (such as arranging it like `all odds, zero, all evens` and then the math to get the matching pair when storing is ` i+ 1+ (def_velocity_set>>1)`...

However such a rearrangement is probably very minor (probably saves 1 instruction).
