### ISSUE TITLE
Vibrating Lines

### ISSUE THREAD

**Issue by Meerkov** [ProjectPhysX/FluidX3D#200]
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/a1efe358-90d3-4970-8795-a1bda7cb6091)

Using one of the default setups, I noticed that the initial state of random noise results in visible grid patterning.

Using recommended setup for Rayleigh Benard Convection demo:
TEMPERATURE
VOLUME_FORCE
D3Q19
FP16S

Is this expected behavior? It looks wrong

The default coloration might be hard to see, so here it is when executed in my custom environment. The vibrating and self-orienting pattern of the random noise should become apparent.
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/c5bb61d8-ff21-42f2-b6f1-cb8f7abbed3f)

Edit: In my sample image of my setup I'm using velocity 0.15 instead of 0.015 as in the demo setup. However it still reproduces, just with lower visibility. Here's example data from a single pixel:
Format is "Frame Number, FPS"
then the `Velocity/c`
```
478 FPS: 253
0.009542987
479 FPS: 251
0.008611688
480 FPS: 250
0.00957845
481 FPS: 250
0.008645571
482 FPS: 251
0.009601751
483 FPS: 251
0.0086692115
484 FPS: 252
```

I picked a pixel at random, and it's changing by about 10% up and down every frame, in a vibrating fashion.

**Comment by Meerkov** [comment]
I removed all the extensions, to try to reduce the problem. You may need to raise the contrast of your monitor to clearly see the patterns, but you can also export the data as I did above to see the raw values are indeed fluctuating, somewhere between 10% and 100% every other pixel.
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/64d21342-61d2-439e-a974-8ee1ed46d940)
Here, I ran 200 frames on six separate instances with torus wrapping (appended into a 6x1 image). The second image had a large droplet of density added.

I have done something special here, `j[ 5] = n/*xp+yp+z0+ side*/;` . This obviously dampens the fluid, but quickly the vibrations are removed.

Please note that there is a macro scale diagonal directional preference, but zero micro scale vibrating lines.

![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/d5e08ef9-c40e-46b9-9adc-7813b092b21d)
Here is an image using the original D2Q9 setup with the j[5] neighbor as normal. Notice here there is both large scale waves, and microscale velocity waves. The density is actually not impacted (!!). I think this might mean that there is some issue with how the velocity fields are exported, but not how the calculations are performed. otherwise I would expect to see these ripples in the density field. But no such artifacting exists.
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/41985c18-9426-406f-9b56-bcfd8dff270d)

This is not limited to D2Q9. Here it is again, on a D3Q27 (with 1 z layer).
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/ed43343e-6e5d-43e9-b974-e5c58983b1a6)
And with 10 z layers
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/1f9b004c-d371-425b-8c15-7d8f7932bbc1)
Going back to where we started, at D2Q9, and negating the j[7] direction by setting that neighbor to `n`, we see the direction of our macroscale ripple change, but again we return to removing all microscale rippling artifacts. I lowered the large density blob so it's more clear that all artifacting is removed.
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/291a5dce-5793-48bf-9e3b-75fffbe2849c)

However, it is not sufficient to remove any direction. Removing the `j[3]` direction results in the microscale artifacts remaining. 
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/cb375b8a-b7af-4290-b480-81c7eedb177d)

You can try using an odd dimensionality (81 pixels instead of 80) but this won't work. You can try changing the `nu` variable to `0.1` which reduces the effect but does not negate it.

However, if you negate any not straight neighbor, the vibrational lines disappear nearly instantaneously.

Given that they show up in both my UI, and FluidX3D's UI, it seems like it's actually a problem with the exporting of the `uxn, uyn,` and ` uzn` variables

**Comment by ProjectPhysX** [comment]
Hi @Meerkov,

the Rayleigh-Benard setup intentionally [initializes the velocity with a bit of random noise](https://github.com/ProjectPhysX/FluidX3D/blob/v2.17/src/setup.cpp#L1284):
```c
		lbm.u.x[n] = random_symmetric(seed[t], 0.015f); // initialize velocity with random noise
		lbm.u.y[n] = random_symmetric(seed[t], 0.015f);
		lbm.u.z[n] = random_symmetric(seed[t], 0.015f);
```
This is to trigger the Rayleigh-Benard instability. It is not a bug.

Kind regards,
Moritz

**Comment by Meerkov** [comment]
You didn't read what I wrote at all, did you.

**Comment by Meerkov** [comment]
Plotting X velocity while cross section looking at the X Y plane of a 64x64x64 grid:
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/3f52dc4f-9a45-4900-8fee-84cdf50cc61f)
Plotting the X velocity while looking through the Y Z plane
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/00229340-ede8-4705-9e7e-8a3a29c6d650)

Plotting X velocity through the X Z plane
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/fff2e88b-f642-4b26-a12e-27220b1bfd4c)


It should be clear that the X velocity is aligned to the X direction in a pattern. It's not random.

**Comment by Meerkov** [comment]
Thanks for re-reading.

>This is expected behavior with LBM. A cartesian grid by its nature is not anisotropic and there is always some leftover grid artifacts.

You're closer, but I think there is still an issue.

This applies at all scales of random noise.
`lbm = Lattice(D=3, Q=27, res=64, Nz=64, sides=6, nu=0.02)`
I'll show you. Each image will be 15 frames after start, showing only the X velocity through the X Y frame. This isn't just any pattern, but an alternating pattern every other frame, which is directly related to the Esoteric Pull algorithm in some way.
`  lbm.velocity[:]=cp.random.uniform(-0.15,0.15, (lbm.N*3), dtype=cp.float32)`
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/648fd56a-c7fb-42d1-8e87-89341578f9b9)
`  lbm.velocity[:]=cp.random.uniform(-0.55,0.55, (lbm.N*3), dtype=cp.float32)`
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/f0001eff-02a0-4379-9e3f-1e73319dcaf6)
`  lbm.velocity[:]=cp.random.uniform(-0.05,0.05, (lbm.N*3), dtype=cp.float32)`
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/636528ef-58be-4574-8850-95261a85d496)

**Comment by Meerkov** [comment]
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/5fd6ed6a-827f-4980-a58e-fe1c34b7755b)
Density calculation, 15 frames,
`  lbm.velocity[:]=cp.random.uniform(-0.05,0.05, (lbm.N*3), dtype=cp.float32)`
Same as the last image in the previous, but notice there is no grid pattern. The density field isn't impacted, only the velocity field.

**Comment by ProjectPhysX** [comment]
The alternating pattern between even/odd time steps comes from the SRT collision operator, that is a known phenomenon.

The streaming scheme does not affect the arithmetic at all. You can replace the streaming algorithm with any other and it is binary identical. It just changes the memory locations where the DDFs are stored. I provide some other streaming algorithms [here in the appendix](https://doi.org/10.3390/computation10060092).

**Comment by Meerkov** [comment]
100 frames with `nu=0.02`
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/9e94fbb7-52de-4c8b-9d51-f7a457f43cd9)
with `nu=0.22`
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/414e3b5a-b9fd-4f5f-894f-ab9f0096c53d)

The artifacts are reduced, sorta, but the fluid also behaves differently. TRT didn't seem to change much.
TRT with `nu=0.02`
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/14b47017-ef3d-4e61-899d-1b5281299cee)

I keep looking at that density field, and how it doesn't have these artifacts. I'm not sure how it could be that if the velocity truly has obvious alternating patterns, that those patterns wouldn't create the same ripples in the density distribution

**Comment by Meerkov** [comment]
I took for a long time reading the code, and I can't determine what causes it.

I decided to use a simple work around, and average the `uxn, uyn, uzn` variables over 2 frames for output purposes only (not impacting the internal calculations). This removes the artifact and provides the expected smooth gradient. 
![image](https://github.com/ProjectPhysX/FluidX3D/assets/8139496/c06fca2b-6df9-47b4-a79c-00ddad53868a)

**Comment by ProjectPhysX** [comment]
Averaging 2 consecutive time steps is indeed a way to smooth over the even/odd oscillations of LBM. Adjusting viscosity `lbm_nu` alone of course changes the physical behavior. But unit conversion usually leaves one free parameter, so you can adjust `lbm_nu` and velocity `lbm_u` together without changing the physics; the Reynolds number $Re=\frac{u}{\nu}\cdot L$ is kept unchanged then. This comes with limits though, as too small `lbm_u` will blow up runtime.

I still owe you an explanation of where exactly the oscilations come from. The SRT collision operator (implemented [here](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/kernel.cpp#L1659)) reads:

$$f_i(\vec{x}, t+\Delta t) = (1-\frac{\Delta t}{\tau})\ f_i^{temp}(\vec{x}, t)+\frac{\Delta t}{\tau}\ f_i^{eq}(\vec{x}, t)$$

For very small viscosuty $\nu\rightarrow 0$, the the relaxation time $\tau=\frac{\nu}{c^2}+\frac{\Delta t}{2}\rightarrow\frac{1}{2}$. Inserting that gives:

$$f_i(\vec{x}, t+\Delta t) = - f_i^{temp}(\vec{x}, t)+2\ f_i^{eq}(\vec{x}, t)$$

If we assume small equilibrium DDFs $f_i^{eq}(\vec{x}, t)\approx 0$ here for simplicity, then the DDFs

$$f_i(\vec{x}, t+\Delta t) = - f_i^{temp}(\vec{x}, t)$$

oscillate between +/- sign in even/odd time steps.

Kind regards,
Moritz

**Comment by Meerkov** [comment]
I appreciate the effort to explain it. Switching to TRT did not change it (this is not SRT specific).

I tried changing just `nu` and `u` but this didn't work.

Can you provide more specific guidance on how to manipulate the default settings to remove the effect? Does the density also need to increase?

Regardless, I think I will stay with my simple hack for now, but I will continue to experiment with these settings based on your feedback.

Thanks for taking a look
