### ISSUE TITLE
Does FluidX3D support multi-component calculations?

### ISSUE THREAD

**Issue by xupeiwust** [ProjectPhysX/FluidX3D#205]
Does FluidX3D support multi-component calculations? For example, in the case of natural gas leakage, the focus is on the content of natural gas in the air after a period of leakage. In addition, for a large scene, such as a range of several kilometers, how fast is FluidX3D calculated? Can it achieve real-time calculation?

**Comment by ProjectPhysX** [comment]
Hi @xupeiwust,

FluidX3D cannot do multiphase/-component. However you can use [passive tracer particles](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#particles-extension) to at least estimate such gas leakage/dilution problems.

You always get at most ~1000³ cells (more accurately, 19 million cells per GB of VRAM). If you make the box large at 1km³, that makes your cells also large at 1m³. If you make the box small at 1mm³, that gives you tiny 1µm³ cells. Fluid flow physics depend on Reynolds number, not on length scale alone.

Real-time is possible at any absolute length scale if you go low enough with resolution, like 100³ cells, or for a 1km³ box 10m³ cells, if that's sufficient for your analysis.

Kind regards,
Moritz

**Comment by xupeiwust** [comment]
thank  you  。I try it
