### ISSUE TITLE
Hitmo

### ISSUE THREAD

**Issue by Ayvsh** [ProjectPhysX/FluidX3D#21]
![Uploading IMG_20221023_211239.jpg…]()

 👋 Hi, I’m @Ayvsh
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

Commit new file

**Comment by Ayvsh** [comment]
Hi

**Comment by ProjectPhysX** [comment]
Hi @Ayvsh, please use this forum only for bugs and questions. Thanks!
