### ISSUE TITLE
Model changing when rotating

### ISSUE THREAD

**Issue by JunchenLyu** [ProjectPhysX/FluidX3D#215]
Hello, I am now trying to do a simulation of rotation, when I successfully load the model, I found that when the model was rotating, some of the meshes had randomly connected together, making the calculation unreliable. Seeking for help! Thanks in advance.
![屏幕截图 2024-08-18 143618](https://github.com/user-attachments/assets/a91f1672-e868-4986-bf43-a0474c8d1474)

**Comment by ProjectPhysX** [comment]
Hi @JunchenLyu,

this happens when the mesh is not watertight, meaning there is holes between triangles or triangles are overlaying.
Try fixing the mesh or reducing triangle count a bit; Microsoft 3D Builder for example can do this.

Kind regards,
Moritz

**Comment by JunchenLyu** [comment]
Thanks a lot!
