### ISSUE TITLE
can't run FluidX3D on popos 22.04, Lenovo ThinkPad T16 Gen 2.

### ISSUE THREAD

**Issue by zrxdaly** [ProjectPhysX/FluidX3D#222]
thanks for the nice solver. I follow the instructions [here](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md) to install it on my Popos 22.04, Lenovo ThinkPad T16 Gen 2. However, it failed.

output of my gpu (Intel® Iris® Xe Graphics):
`lshw -c video`

> *-display                 
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 04
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1200
       resources: iomemory:600-5ff iomemory:400-3ff irq:188 memory:603c000000-603cffffff memory:4000000000-400fffffff ioport:2000(size=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff

i tried to install opencl runtime following:
`sudo apt update && sudo apt upgrade -y
sudo apt install -y g++ git make ocl-icd-libopencl1 ocl-icd-opencl-dev intel-opencl-icd
sudo usermod -a -G render $(whoami)
sudo shutdown -r now`

after this, `./make.sh ` still gives me that 
`Error: No OpenCL devices are available. Please install the drivers for your |
|        GPU(s) and/or the CPU Runtime for OpenCL. Instructions: 
`
could anyone help? thanks

**Comment by ProjectPhysX** [comment]
Hi @zrxdaly,

in case there is problems with the Intel OpenCL GPU runtime from the package manager on a certain distro, you can also [install the packages manually](https://github.com/intel/compute-runtime/releases):

```bash
export IGCV="1.0.17384.11"
export CRTV="24.31.30508.7"
export ILZV="1.3.30508.7"
sudo apt install -y g++ git make ocl-icd-libopencl1 ocl-icd-opencl-dev
mkdir -p ~/neo
wget -P ~/neo https://github.com/intel/intel-graphics-compiler/releases/download/igc-${IGCV}/intel-igc-core_${IGCV}_amd64.deb
wget -P ~/neo https://github.com/intel/intel-graphics-compiler/releases/download/igc-${IGCV}/intel-igc-opencl_${IGCV}_amd64.deb
wget -P ~/neo https://github.com/intel/compute-runtime/releases/download/${CRTV}/intel-level-zero-gpu-dbgsym_${ILZV}_amd64.ddeb
wget -P ~/neo https://github.com/intel/compute-runtime/releases/download/${CRTV}/intel-level-zero-gpu_${ILZV}_amd64.deb
wget -P ~/neo https://github.com/intel/compute-runtime/releases/download/${CRTV}/intel-opencl-icd-dbgsym_${CRTV}_amd64.ddeb
wget -P ~/neo https://github.com/intel/compute-runtime/releases/download/${CRTV}/intel-opencl-icd_${CRTV}_amd64.deb
wget -P ~/neo https://github.com/intel/compute-runtime/releases/download/${CRTV}/libigdgmm12_22.4.1_amd64.deb
sudo dpkg -i ~/neo/*.deb
sudo usermod -a -G render $(whoami)
rm -r ~/neo
```

Kind regards,
Moritz
