### ISSUE TITLE
Model conflict in rotation

### ISSUE THREAD

**Issue by JunchenLyu** [ProjectPhysX/FluidX3D#223]
When I try to simulate the meshing and rotation of two gears, I find that one gear is intermittently covered by the model of the other gear. Is this normal? How should I debug? Thank you in advance for your reply!
<img width="335" alt="10464905106df78fab72c4977a315dd" src="https://github.com/user-attachments/assets/395b5737-6fc8-4cad-b544-aa7ca94b73aa">
<img width="359" alt="795fced91c4730966ffadfdd98c14f0" src="https://github.com/user-attachments/assets/f3fad61e-7b5e-45a3-8afe-18ae16463fca">

**Comment by ProjectPhysX** [comment]
Hi @JunchenLyu,

this is a special case I have not yet considered. One gear is in the voxelization bounding box of the other, so its teeth get cut off.
I have just [fixed](https://github.com/ProjectPhysX/FluidX3D/commit/584f10a382b47cdec5972bcae27bbc83a8c70b23) this, now the teeth of the other gear which have different velocity will not be unvoxelized and it works as intended. Please pull the latest update!

Kind regards,
Moritz

**Comment by JunchenLyu** [comment]
Thanks a lot!
