### ISSUE TITLE
Unnecessary Solid layer in Temperature Example

### ISSUE THREAD

**Issue by Meerkov** [ProjectPhysX/FluidX3D#228]
https://github.com/ProjectPhysX/FluidX3D/blob/584f10a382b47cdec5972bcae27bbc83a8c70b23/src/setup.cpp#L1310C3-L1310C124

It seems like this has 2 layers of solid cells in this example, but if I understand correctly, only 1 layer of solid cells is necessary since Z neighbors will wrap around to the other side.

This means you need like 1/256 less memory, which should save on cache misses.

**Comment by ProjectPhysX** [comment]
Hi @Meerkov,

the duplicate top boundary is for rendering purposes. For the setup itself it is indeed not required.

Kind regards,
Moritz

**Comment by Meerkov** [comment]
Thanks for confirming!
