### ISSUE TITLE
sq(uz) used in 2D simulation causes density drain

### ISSUE THREAD

**Issue by Meerkov** [ProjectPhysX/FluidX3D#229]
https://github.com/ProjectPhysX/FluidX3D/blob/584f10a382b47cdec5972bcae27bbc83a8c70b23/src/kernel.cpp#L1026

I think in practice the unguarded `sq(uz)` here causes the density to drop rapidly in 2D sims when UZ set. It's not clear that UZ should have any impact in a 2D simulation, so I recommend guarding with a `#ifndef D2Q9`.

This bug impacted my setup, since I was setting Ux Uy and Uz by default, and just switching the DQ without changing the velocity setup. Adding the `ifndef` guard fixed my issue.

**Comment by Meerkov** [comment]
```c++
    const float c3 = -3.0f * (sq(ux) + sq(uy)
#ifndef D2Q9
	+ sq(uz) // Protect 2D Simulations from Z velocity messing with calculations! Bugfix!
#endif
	), rhom1 = rho - 1.0f; // c3 = -2*sq(u)/(2*sq(c)), rhom1 is arithmetic optimization to minimize digit extinction
```

Here's with the bugfix.

**Comment by ProjectPhysX** [comment]
Hi @Meerkov,

thanks for finding and reporting this bug! Have [fixed it](https://github.com/ProjectPhysX/FluidX3D/commit/81604e3ae140571b39aaff4533837e3502686a68#diff-464b1d19d4b616b9609031b48429081b2c215328d9f98bc5cbeac6b2b84fdbf3R1032)!

Kind regards,
Moritz
