### ISSUE TITLE
Mesh translation

### ISSUE THREAD

**Issue by trparry** [ProjectPhysX/FluidX3D#23]
Hello, thank you for making this awesome project available! After getting the star wars tie fighter working, I was looking at how you rotated the mesh before revoxelizing. In setup.cpp you make a matrix called rotation and pass it to the rotate function. Is it possible to also translate the mesh, or is the mesh always constrained to the "center" point that you define when you use read_stl? Perhaps I'm not interpreting this correctly. Translating the mesh would be useful to observe the interaction between two solid geometries within the simulation domain, where the two geometries could be both rotating and translating dynamically. Thanks for any clarification!

**Comment by ProjectPhysX** [comment]
Thanks for bringing this up! A translation function was indeed missing. I just added it in release v1.2. You can now use:
```c
mesh.translate(const float3& translation);
```
