### ISSUE TITLE
Possible Improvement: Guard Updates with flag

### ISSUE THREAD

**Issue by Meerkov** [ProjectPhysX/FluidX3D#230]
https://github.com/ProjectPhysX/FluidX3D/blob/584f10a382b47cdec5972bcae27bbc83a8c70b23/src/kernel.cpp#L1591-L1607

Imagine you have your kernel running 200 FPS. You're still probably only rendering 60 FPS worth of frames when using Update Graphics. I'm not sure if it's results in much of an improvement, but it seems like you can avoid some writes like this:

Also, reversing the nesting of UPDATE_FIELDS and EQUILIBIRUM_BOUNDARIES allows the code to be less redundant. In my example, I pass an extra argument `draw` to the streaming function to ensure that I only write to output memory when that frame will be used for graphics.
```c++
#ifdef UPDATE_FIELDS
    if (draw)
    {
#ifdef EQUILIBRIUM_BOUNDARIES
	if(flagsn_bo!=TYPE_E) { // only update fields for non-TYPE_E cells
#else // EQUILIBRIUM_BOUNDARIES
	{ // Empty If
#endif // EQUILIBRIUM_BOUNDARIES
        rho[n] = rhon; // update density field
        u[n] = uxn; // update velocity field
        u[def_N + (ulong) n] = uyn;
        u[2ul * def_N + (ulong) n] = uzn;
		}
	}
#endif // UPDATE_FIELDS
```

The speed improvement seemed inconclusive to me. I think it was a small increase. The extra `branch` may only be beneficial if you're ensuring the `draw` flag is `false` at least half the time.

**Comment by Meerkov** [comment]
Tests on my custom version imply something like a 10-15% speedup by adding the `draw` flag guard. This improved my custom demo that was running 1900 FPS up to 2200 FPS.

**Comment by ProjectPhysX** [comment]
Hi @Meerkov,

originally `UPDATE_FIELDS` was intended for exactly this purpose, to not have `stream_collide()` update `rho`/`u` at all and instead only let the rendering thread update `rho`/`u` before rendering each frame, using the `update_fields()` kernel. This is used for headless mode rendering (normal `GRAPHICS` mode) still.
However with `INTERACTIVE_GRAPHICS` there is threading issues: when the `update_fields()` dispatch is inserted in between `stream_collide()` and `increment_time_step()`, flickering will be visible. So for now I just enabled `UPDATE_FIELDS` for `INTERACTIVE_GRAPHICS` as a workaround.

I want to keep `stream_collide()` entirely separate from the rendering part, so the `draw` guard flag is not an option. Will think about how to resolve the threading issues to make my original implementation work.

Kind regards,
Moritz

**Comment by Meerkov** [comment]
Makes sense.

My code is currently:
```cpp
#ifdef UPDATE_FIELDS
    if (draw
#ifdef EQUILIBRIUM_BOUNDARIES
	    && flagsn_bo!=TYPE_E // only update fields for non-TYPE_E cells
#endif // EQUILIBRIUM_BOUNDARIES
	) {
    rho[               n] = rhon; // update density field
    u[                 n] = uxn; // update velocity field
    u[    def_N+(ulong)n] = uyn;
    u[2ul*def_N+(ulong)n] = uzn;
}
#endif // UPDATE_FIELDS
```

but without the draw flag, it's just a refactoring for readability and reducing the nesting clauses.

```cpp
#ifdef UPDATE_FIELDS
#ifdef EQUILIBRIUM_BOUNDARIES
    if( flagsn_bo!=TYPE_E) // only update fields for non-TYPE_E cells
#endif // EQUILIBRIUM_BOUNDARIES
    {
    rho[               n] = rhon; // update density field
    u[                 n] = uxn; // update velocity field
    u[    def_N+(ulong)n] = uyn;
    u[2ul*def_N+(ulong)n] = uzn;
}
#endif // UPDATE_FIELDS
```
