### ISSUE TITLE
Incorrect folder during writing to a file

### ISSUE THREAD

**Issue by rodionstepanov** [ProjectPhysX/FluidX3D#236]
I've just run Concorde example. I got writing of files `FluidX3D-2.png` and `FluidX3D-2.txt` in folder `D:/`. I've checked that get_exe_path() returns correct path `D:/FluidX3D-2.19/bin/` Something wrong is going in `create_file_extension` that I cannot trace. Looks like a point `.` in the path considered as and of file name.

**Comment by ProjectPhysX** [comment]
Thanks for reporting this bug! [Fixed](https://github.com/ProjectPhysX/FluidX3D/commit/520b522dbfdc1b68c42fc2b0fe43448ce68fa41d)!
