### ISSUE TITLE
Error: "graphics" is not a member of "LBM" when running Ahmed body sample

### ISSUE THREAD

**Issue by HONGCAO-Z** [ProjectPhysX/FluidX3D#239]
Hi all,

I'm encountering an issue while running the Ahmed body sample. Specifically, I'm getting a C++ compiler error:
C2039: 'graphics' is not a member of 'LBM', and the sample fails to run.

I've imported a binary .stl file as part of the process. Is anyone else experiencing the same issue, or could there be something I'm missing?

Any help or guidance would be appreciated!

Thanks in advance.

**Comment by ProjectPhysX** [comment]
Hi @HONGCAO-Z 

comment out [`BENCHMARK`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/defines.hpp#L16), and uncomment [`INTERACTIVE_GRAPHICS`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/defines.hpp#L27) or [`GRAPHICS`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/defines.hpp#L29) in `defines.hpp`. Then recompile.

Kind regards,
Moritz
