### ISSUE TITLE
OpenCL and its version / extension.

### ISSUE THREAD

**Issue by Friedrich2** [ProjectPhysX/FluidX3D#251]
_Not_ a bug, just a few questions out of pure interest regarding this fantastic program:
In the README file, you mentioned OpenCL version 1.2. Being an OpenCL novice, I was not able to determine if this was really the minimal version you used in the source code.
- Do you use OpenCL 3.0, or was it a conscious decision due to compatibility reasons to explicitly use solely OpenCL 1.2?
- How is your policy regarding using device-specific extensions if available? (Do I understand https://github.com/ProjectPhysX/FluidX3D/blob/014e7eefb8a6e335a940ae3076dba86d93d991eb/src/opencl.hpp correctly that they are used if available?)
- If you use extensions, do you have some kind of test suite or so to conserve the quality by taking the different if-branches?

**Comment by ProjectPhysX** [comment]
Hi @Friedrich2,

OpenCL 3.0 today is the most common standard for the _OpenCL SDK_ - but under the hood the _OpenCL C language standard_ still follows 1.2 specification. You'll find this when you query [`CL_DEVICE_OPENCL_C_VERSION`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/opencl.hpp#L110) which is 1.2 for pretty much all GPUs, in contrast to `CL_DEVICE_OPENCL_VERSION` which reports 3.0 on most devices.

 3.0 is really just a rebranding of 1.2, with the addition of a framework for some optional vendor-specific extensions. The reasoning here was that the in-between versions 2.0-2.2, which really added new mandatory feature sets, were only ever implemented by AMD, Intel and ARM in hardware, but not Nvidia, so code written for 2.0-2.2 was never universally compatible with Nvidia GPUs too. So Khronos had to back-track to 1.2.

To have universally compatible code, you have to adhere to OpenCL C 1.2 language standard - or at least need a 1.2-compatible fallback implementation if the 3.0 extensions are not available. An example here is my new [atomic floating-point addition](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/kernel.cpp#L1943) function, which if available uses hardware-supported instructions through inline PTX assembly (Nvidia), vendor-specific OpenCL 3.0 extension functions (Intel/AMD), or a universally compatible OpenCL 1.2 fallback emulation variant. All variants do the same thing, only performance is a little different. I have no particular framework to test, I just use a relevant sample setup and tested each variant on every type of hardware to make sure it works everywhere and performance is better than fallback.

Some extensions are already part of 1.2 spec, like FP64 and FP16 arithmetic support - yet not available on all GPUs. For example Nvidia Maxwell and earlier lacks FP16 arithmetic support, and Intel Arc Alchemist lacks FP64 arithmetic support. Both have to be manually turned on during OpenCL compiling, and my [OpenCL-Wrapper](https://github.com/ProjectPhysX/OpenCL-Wrapper) does so automatically if these extensions are available. In FluidX3D I'm not using FP64/FP16 arithmetic at all though, as FP32 is sufficient and universally compatible.

Kind regards,
Moritz
