### ISSUE TITLE
Aerodynamics of a simple wing - simulation setup question

### ISSUE THREAD

**Issue by YevheniiKovryzhenko** [ProjectPhysX/FluidX3D#252]
First of all, thank you a lot for your work! I went through all the examples and the tools just looks amazing! I am in search for some alternative CFD tool and your cross-platform minimal-footprint project fits my needs perfectly on paper, so I wanted to give it a try. 

I went through all the examples without any major issue (I only needed to adjust the amount of memory allocated since I only have 3060TI), so I don't think I have any issues with the drivers and/or installation (the results for all the test cases with STL imported geometries looked fine). I started by considering a simple wing model that I made in SOLIDWORKS and exported as STL. I did check the geometry for possible issues using blender and even tried reducing the export fidelity to make sure that is not the problem. I have also tested this exact setup on two different machines running Win11 and Ubuntu 24 with the exact same result (both have 3060Ti, one has core i5 13600k and the other one has 14600k). Everything is fine until I start the simulation (imported stl geometry looks fine to me):

![image](https://github.com/user-attachments/assets/160eaf1a-0033-4100-b240-972a447af077)

I start the simulation but pause after just 1 second:
![image](https://github.com/user-attachments/assets/d1fae4fc-e313-44e0-b4d9-caca1341d560)

**Actual problem description**. Once the simulation is started, I get a few seconds of everything looking alright, but then suddenly I see a massive number of white "spikes" coming out of the geometry and the turbulent swirls change/disappear from large portions of the model. If these where happening at a certain location, I could blame the stl file for being overly fine or coarse at certain places, but since these spikes are fairly random and update every 2-3 seconds I doubt that after a successful stl import the stl even makes a difference. 

Geometry after simulation has updated for 2-3 seconds and ran into the first "corruption event":
![image](https://github.com/user-attachments/assets/3910cfa4-6c3f-4ac9-83d7-ca67e3f16cb8)

This will continue to happen every 2-3 seconds until it settle's down:
![image](https://github.com/user-attachments/assets/0f9a86cf-576d-4987-b1e8-8c0cf28d534c)

Or explode:
![image](https://github.com/user-attachments/assets/c2765082-a2a6-46a0-9093-b38087b1753e)

Notice how the geometry appears to go away almost entirely. This is only present when running on Win11 version. I got the same while spikes when running on Linux, but I think the geometry was still present beneath it. If it was not clearly affecting the flow I would not care at all, but it has definitely something to do with convergence... Adjusting velocity of the lbm seem to greatly effect this, but I could not find a value that removes this issue. 

This is also my first "real" example so I am sure I could have made a mistake somewhere which causes this, so please check this out first before digging any deeper:

```
void main_setup() { //CH10SH Wing Study; required extensions in defines.hpp: FP16S, FORCE_FIELD, EQUILIBRIUM_BOUNDARIES, SUBGRID, optionally INTERACTIVE_GRAPHICS
	// ################################################################## define simulation box size, viscosity and volume force ###################################################################
	// setup control flags/settings:
	const std::string test_case_name = "CH10SH"; //stl model name and for logging directory name
#define LOG_DATA false //enable/disable data printout to text file
#define PRINT_DATA false //enable/disable data printout to console	 
	const uint memory = 7000u; // available VRAM of GPU(s) in MB
	
	//flow parameters:
	const float u_lbm = 0.15f; //simulation flow speed
	const float u_si = 30.0f; //si flow speed [m/s]
	const float nu_si = 1.48E-5f;
	const float rho_si = 1.225f; // flow density [kg/m3]
	
	//test box parameters:
	const float X_si=2.0f; //m
	const float Y_si=1.5f; //m
	const float Z_si=0.3f; //m
	const float box_scale = 1.2f;

	//simulation time:
	const float T_si = 0.25f; //time [s]

	//other:
	const float A_si = 0.03*1.5; // m2 reference area (for aero forces)

	// Initial setup (memory allocation and scaling)
	const float Lx_si = units.x(box_scale*X_si);
	const float Ly_si = units.x(box_scale*Y_si);
	const float Lz_si = units.x(0.5f*(box_scale-1.0f)*Y_si+Z_si);
	const uint3 N_lbm = resolution(float3(Lx_si, Ly_si, Lz_si), memory); // input: simulation box aspect ratio and VRAM occupation in MB, output: grid resolution
	units.set_m_kg_s((float)N_lbm.y, u_lbm, 1.0f, box_scale*Y_si, u_si, rho_si);

	const float nu_lbm = units.nu(nu_si);
	const ulong T_lbm = units.t(T_si);
	const float lbm_scale_length = units.x(X_si);

#if PRINT_DATA 
	print_info("Re = "+to_string(to_uint(units.si_Re(Y_si, u_si, nu_si))));
#endif

	LBM lbm(N_lbm, nu_lbm);
	// ###################################################################################### define geometry ######################################################################################
	// import stl:
	const float3 offset = lbm.center() - float3(units.x(0.2f*(box_scale*X_si)), 0.0f, 0.0f);
	Mesh* wing = read_stl(get_exe_path()+"../stl/"+test_case_name+".stl", lbm.size(), offset, float3x3(float3(1, 0, 0), radians(90.0f)), lbm_scale_length);
	
	// render:
	lbm.voxelize_mesh_on_device(wing, TYPE_S);
	
	//setup boundary conditions:
	const uint Nx=lbm.get_Nx(), Ny=lbm.get_Ny(), Nz=lbm.get_Nz(); parallel_for(lbm.get_N(), [&](ulong n) { uint x=0u, y=0u, z=0u; lbm.coordinates(n, x, y, z);
		if(lbm.flags[n]!=TYPE_S) lbm.u.x[n] = u_lbm;
		if(x==0u||x==Nx-1u||y==0u||y==Ny-1u||z==0u||z==Nz-1u) lbm.flags[n] = TYPE_E; // all non periodic	
	}); // ####################################################################### run simulation, export images and data ##########################################################################
	lbm.graphics.visualization_modes = VIS_FLAG_SURFACE|VIS_Q_CRITERION;
	lbm.graphics.set_camera_centered(20.0f, 30.0f, 10.0f, 1.648722f);
	lbm.run(0u, T_lbm); // initialize simulation

	
#if LOG_DATA //setup path for data logging
	string path;
	time_t now = time(0);
	tm *ltm = localtime(&now);
	const string unique_fldr_name = to_string(ltm->tm_year+1900)+"_"+to_string(ltm->tm_mon)+"_"+to_string(ltm->tm_mday)+"_"+to_string(ltm->tm_hour)+"_"+to_string(ltm->tm_min)+"_"+to_string(ltm->tm_sec)+"/";
	
#if defined(FP16S)
	path = get_exe_path()+"logs/"+test_case_name+"FP16S/"+to_string(memory)+"MB/"+unique_fldr_name;
#elif defined(FP16C)
	path = get_exe_path()+"logs/"+test_case_name+"FP16C/"+to_string(memory)+"MB/"+unique_fldr_name;
#else // FP32
	path = get_exe_path()+"logs/"+test_case_name+"FP32/"+to_string(memory)+"MB/"+unique_fldr_name;
#endif // FP32

#if PRINT_DATA
	print_info("Logging directory: " + path + "\n");
#endif
	
	lbm.write_status(path);
	write_file(path+"forces_lbm.csv", "t,Fx,Fy,Fz\n");
	write_file(path+"forces_si.csv", "t,Fx,Fy,Fz\n");
	write_file(path+"aero.csv", "t,Cd,Cl\n");
#endif

	// println();
	while(lbm.get_t()<=T_lbm) { // main simulation loop
		if(lbm.graphics.next_frame(T_lbm, 5.0f)) {
			lbm.calculate_force_on_boundaries();
			lbm.F.read_from_device();
			
			const float t_lbm = lbm.get_t();
			const float3 forces_lbm = lbm.calculate_force_on_object(TYPE_S);
			
			const float t_si = units.t(t_lbm);
			const float3 forces_si = float3(units.si_F(forces_lbm.x), units.si_F(forces_lbm.y), units.si_F(forces_lbm.z));
			
			const float Cd = forces_si.x/(0.5f*rho_si*sq(u_si)*A_si);
			const float Cl = forces_si.z/(0.5f*rho_si*sq(u_si)*A_si);

#if PRINT_DATA
			print("\r"\
				"Fx="+to_string(forces_si.x, 4u)+", "+\
				"Fy="+to_string(forces_si.y, 4u)+", "+\
				"Fz="+to_string(forces_si.z, 4u)+", "+\
				"Cd="+to_string(Cd, 4u)+", "+\
				"Cl="+to_string(Cl, 4u)+"                                                                               ");
#endif
			
#if LOG_DATA 
			write_line(path+"forces_lbm.csv",\
				to_string(t_lbm, 4u)+","+\
				to_string(forces_lbm.x, 4u)+","+\
				to_string(forces_lbm.y, 4u)+","+\
				to_string(forces_lbm.z, 4u)+"\n");

			write_line(path+"forces_si.csv",\
				to_string(t_si, 4u)+", "+\
				to_string(forces_si.x, 4u)+","+\
				to_string(forces_si.y, 4u)+","+\
				to_string(forces_si.z, 4u)+"\n");

			write_line(path+"aero_si.csv",\
				to_string(t_si, 4u)+","+\
				to_string(Cd, 4u)+","+\
				to_string(Cl, 4u)+"\n");
#endif
			 
#if defined(GRAPHICS) && !defined(INTERACTIVE_GRAPHICS)
			//lbm.graphics.write_frame(path+"images/");
#endif // GRAPHICS && !INTERACTIVE_GRAPHICS
		}
		lbm.run(1u, T_lbm);
	}
#if LOG_DATA
	lbm.write_status(path);
#endif
} /**/
```

STL file: 
[CH10SH.zip](https://github.com/user-attachments/files/18158300/CH10SH.zip)

Any and all help will be much appreciated!

**Comment by ProjectPhysX** [comment]
Hi @YevheniiKovryzhenko,

those white spikes are visualization of the force vectors on the individual grid cells - see the low-pressure region above the wing? In interactive visualization you can toggle them with key <kbd>1</kbd>, or in the setup function as `lbm.graphics.visualization_modes` with `VIS_FLAG_SURFACE` and/or `VIS_FLAG_SURFACE`. The force visualization is enabled as part of the `FORCE_FIELD` extension.
Rest of the setup looks good; I would only decrease `u_lbm = 0.075f;`.

Kind regards,
Moritz

**Comment by YevheniiKovryzhenko** [comment]
@ProjectPhysX, it is actually quite funny that it never occurred to me that those are force vectors... I did not even realize you added that feature!

Anyways, thanks a lot! By the way, any luck with implementing that boundary wall function to improve the accuracy of the aerodynamic forces?

**Comment by ProjectPhysX** [comment]
Hi @YevheniiKovryzhenko,

`u_lbm` is a (kind of) free parameter. Its exact choice has no effects on the physics of the system. However large value `>0.1` will cause density oscillations and even larger values cause instability. The smaller the value, the more time steps the simulation has to compute - `u_lbm` is inverse proportional to simulation runtime. Ideally you want to choose it as large as possible, but small enough to not have non-physical artifacts like density fluctuations. From my testing, the ideal value is around `0.075`.

No luck yet with the boundary model. I'm stuck with the literal corner case in 3D where specular reflection of DDFs reflect them from space diagonals to axis-aligned directions, which causes trouble with the different collision operator weights for those directions. There is no solution to this in literature either.

Kind regards,
Moritz
