### ISSUE TITLE
[Question] What is the meanig of flags

### ISSUE THREAD

**Issue by Yujif1Aero** [ProjectPhysX/FluidX3D#26]
Hi,

Thank your for sharing your CFD code. I have a question to your codes.
After runing your code, I got the date of flags. I coudnt understand this date.
Could you teach me?

Best,

**Comment by ProjectPhysX** [comment]
Hi @Yujif1Aero, what exactly do you mean with "date of flags"?

**Comment by Yujif1Aero** [comment]
Thank you for your replying@ProjectPhysX . I couldnt undastand Toggle rendering modes with the keyboard:
1: flags in the section "How to get started?" No.4 of readme file. Is it pysics value?

**Comment by ProjectPhysX** [comment]
The `lbm.flags[n]` data field contains an 8-bit integer for every grid point. If it's `00000000`, it's a standard fluid voxel, if it's `00000001`, it's a solid voxel, if it's `00000010`, it's equilibrium boundary (inflow/outflow). The other bits are used for other types.

If you have a voxelized solid geometry in the box, the "flags" rendering mode with key `1` draws the outline of the solid geometry. And it also marks inlet/outlet (equilibrium boundary) voxels and other boundary conditions, if present. These rendering modes are just for visualization, they have no impact on the physics/simulation.
