### ISSUE TITLE
GeForce9600GT dose not working

### ISSUE THREAD

**Issue by tyrafluid** [ProjectPhysX/FluidX3D#34]
Hi @ProjectPhysX ,
First of all, thank you for opening your fantastic code.
I got an error that I could not deal with.
I use GeForce 9600GT and I tried "#define USE_OPENCL_1_1" .
In spite of that it dose not calculate anything.
What is problem?
Could you tell me the reason?
My GeForce driver version is 342.01(the newest for my GPU)
![image](https://user-images.githubusercontent.com/117583582/200177715-dc0b61c0-abe6-45a6-a627-a7b379e396fe.png)

Thank you.

**Comment by ProjectPhysX** [comment]
Hi @tyrafluid, I've had the same issue testing the Quadro NVS 290. `local` memory is not yet supported in OpenCL 1.0. Luckily, I use local memory only in the voxelisation, which is not essential. The solution is simple: in `src/kernel.cpp`, starting at line 1867, replace the entire `voxelize_mesh` kernel function with this:
```c
)+R(kernel void voxelize_mesh(global uchar* flags, const uchar flag, const global float* p0, const global float* p1, const global float* p2, const uint triangle_number, float x0, float y0, float z0, float x1, float y1, float z1) { // voxelize triangle mesh
	const uint n = get_global_id(0); // n = x+(y+z*Ny)*Nx
	const float3 p = position(coordinates(n))+(float3)(0.5f*(float)def_Nx-0.5f, 0.5f*(float)def_Ny-0.5f, 0.5f*(float)def_Nz-0.5f);
	if(p.x<x0||p.y<y0||p.z<z0||p.x>x1||p.y>y1||p.z>z1) return; // return straight away if grid point is outside the bounds of the mesh (~4x faster)
	for(uint i=0u; i<triangle_number; i++) {
		const float3 p0i = (float3)(p0[3u*i], p0[3u*i+1u], p0[3u*i+2u]);
		const float3 p1i = (float3)(p1[3u*i], p1[3u*i+1u], p1[3u*i+2u]);
		const float3 p2i = (float3)(p2[3u*i], p2[3u*i+1u], p2[3u*i+2u]);
		const float3 u=p1i-p0i, v=p2i-p0i;
		{
			const float3 w=r0_origin-p0i, h=cross(r0_direction, v), q=cross(w, u);
			const float f=1.0f/dot(u, h), s=f*dot(w, h), t=f*dot(r0_direction, q);
			intersections_0 += (uint)(s>=0.0f&&s<=1.0f&&t>=0.0f&&s+t<=1.0f&&f*dot(v, q)>0.0f);
		} {
			const float3 w=r1_origin-p0i, h=cross(r1_direction, v), q=cross(w, u);
			const float f=1.0f/dot(u, h), s=f*dot(w, h), t=f*dot(r1_direction, q);
			intersections_1 += (uint)(s>=0.0f&&s<=1.0f&&t>=0.0f&&s+t<=1.0f&&f*dot(v, q)>0.0f);
		}
	}
	if(intersections_0%2u&&intersections_1%2u) flags[n] = flag;
} // voxelize_mesh()
```

**Comment by tyrafluid** [comment]
Thank you for quick responding. I got another errors.
![image](https://user-images.githubusercontent.com/117583582/200582637-0aa6a102-f0e5-4e7c-8b7a-d758433d063d.png)
 I added "const float3 p0i = (float3)(p0[3u * i], p0[3u * i + 1u], p0[3u * i + 2u]);
		const float3 p1i = (float3)(p1[3u * i], p1[3u * i + 1u], p1[3u * i + 2u]);
		const float3 p2i = (float3)(p2[3u * i], p2[3u * i + 1u], p2[3u * i + 2u]);
		const float3 u = p1i - p0i, v = p2i - p0i;"
.

However, my gpu havent got enough memory....
![image](https://user-images.githubusercontent.com/117583582/200583086-05ab46ab-fcb2-4ef1-b030-49e71c45967d.png)

**Comment by ProjectPhysX** [comment]
@tyrafluid oh I missed a few lines. See the updated `voxelize_mesh` kernel again and copy/paste it in your code.
With the memory, the default benchmark uses a 256³ box which is too large for the 9600 GT. In [`src/setup.cpp`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/setup.cpp#L946) in line 946, change resolution down to 176³, then it should work.
