### ISSUE TITLE
About updating density and velocity

### ISSUE THREAD

**Issue by tyrafluid** [ProjectPhysX/FluidX3D#37]
Hi @ProjectPhysX ,

I would like to know the difference between when I use this option and when I dont use this option.
![image](https://user-images.githubusercontent.com/117583582/200584808-7d8563ff-7d0f-43d7-8844-70ebf9825548.png)

As long as I use this option, density and velocity arent updated during time marching?
Moreover, could you teach me how I set up this option.

Thank you

**Comment by tyrafluid** [comment]
@ProjectPhysX 
I want to know how to read your code. Could you teach me if possible?

**Comment by ProjectPhysX** [comment]
Hi @tyrafluid! By default, density and velocity are not updated during time marching. Only when you call `lbm.update_fields();` in `main_setup()` explicitly, they are updated in GPU memory, and a subsequent `lbm.rho.read_from_device();`/`lbm.u.read_from_device();` brings them in CPU memory to evaluate by accessing `lbm.rho[n]`/`lbm.u.x[n]`/`lbm.u.y[n]`/`lbm.u.z[n]`.

If you want density and velocity do be updated during time marching, you can add the line `#define UPDATE_FIELDS` somewhere in `src/defines.hpp`.

**Comment by tyrafluid** [comment]
Thank you @ProjectPhysX
I want to know how to read the your code. First of all, I would like to learn the structure of your code. Could you teach me if possible?
