### ISSUE TITLE
Old AMD GPU does not successfully compile OpenCL C code

### ISSUE THREAD

**Issue by BurgaoTheChamp** [ProjectPhysX/FluidX3D#4]
![image](https://user-images.githubusercontent.com/94881470/188880484-b6425708-78d4-45c4-90c0-4d31121fe9c2.png)
The warnings look to be simple mistakes ";" or "(" begin expected but I don't know what those files are or what for and there aren't in that file path anyways.

I tried to uncomment "#define USE_OPENCL_1_1" but as I expected it wouldn't work anyways. The kernel.cpp, I didn't even look at it because I didn't change anything.

**Comment by ProjectPhysX** [comment]
Thank you for the bug report!
The OpenCL C code itself in all these places is correct, so this seems to be an issue with the C++ stringification macro being confused with brackets by your compiler. Unfortunately I can't replicate this on any of my systems. What compiler version do you use?
Try this: In `src/kernel.cpp`, replace `)+") {"+R( // ...` with `)+")"+R( { // ...` in lines 1278, 1385 and 1725. Let me know if it works, then I'll update it in the repository.

**Comment by BurgaoTheChamp** [comment]
I'm using this version
![image](https://user-images.githubusercontent.com/94881470/189248141-619fff4a-dc1b-4af6-9fae-2dee8a67e2ec.png)
I'll try to do that suggestion and I'll report soon about the kernel.cpp

**Comment by BurgaoTheChamp** [comment]
Same error
![image](https://user-images.githubusercontent.com/94881470/189250992-eae193fc-fa76-4a1a-abb9-fdf77bf56532.png)
btw I updated my compiler too
![image](https://user-images.githubusercontent.com/94881470/189251091-7278d074-c8a2-47c4-a5cc-d96e59344963.png)

**Comment by PavelBlend** [comment]
I am getting the same error. I am using exe files from release:
https://github.com/ProjectPhysX/FluidX3D/releases/tag/v1.0

I don't know how to compile sources myself.

My CPU:
AMD A8-5600K APU with Radeon(tm) HD Graphics

Integrated GPU:
AMD Radeon HD 7560D ATI Technologies Inc. 4.5.13399 Core Profile Context 15.201.1151.1008

External GPU:
Missing

I run the program like this:
`FluidX3D-Benchmark-FP32-FP16C-Windows.exe 0`

or so:
`FluidX3D-Benchmark-FP32-FP16C-Windows.exe 1`

**Comment by PavelBlend** [comment]
I was able to run FluidX3D-Benchmark-FP32-FP32-Windows.exe on a GeForce GT 710.

**Comment by Shubham-wiz** [comment]
FluidX3D-Benchmark-FP32-FP32-Windows.exe working fine on amd 5600x with 3060

**Comment by ProjectPhysX** [comment]
It seems this is a driver bug with some very old AMD/ATI toasters.
With such driver bugs there sometimes is the possibility to avoid them with weird code circumventions and/or contacting the AMD driver team. But I would need to have the hardware to try&error-fix this, so unfortunately there is not really something I can do. I'll leave this thread open in case someone of you finds a solution.

**Comment by Yujif1Aero** [comment]
@ProjectPhysX Thank you so much for your taking your time for me. I will try it. 
I super appreciate you.

**Comment by Yujif1Aero** [comment]
Thank you for replying @ProjectPhysX . Sorry, your modified code doesnt work.
However, I have tried to modify your code, and I have got the solution.
I have modified TYPE number to GPU like this,
![image](https://user-images.githubusercontent.com/116667889/200612046-421993e4-fd0e-4969-bd1f-57816256ae10.png)

Due to it, your code is working now!!!
![image](https://user-images.githubusercontent.com/116667889/200612205-0545de81-9d34-41b5-89e0-eb36191fe214.png)

Could you review this? Let me know this solution is correct!!!

Yuji,
Best,

**Comment by Yujif1Aero** [comment]
@ProjectPhysX 
Calculation is done. My GPU bench mark is here.
![image](https://user-images.githubusercontent.com/116667889/200618740-ed6f0bcc-d42e-4057-8329-c8189ac3532f.png)

**Comment by ProjectPhysX** [comment]
Hi @Yujif1Aero, thank you so much for finding the culprit! It seems that the old AMD compiler cannot handle binary-formatted number literals. Changing to hexadecimal notation fixes that of course.

**Comment by Yujif1Aero** [comment]
Thank your for quick updating @ProjectPhysX.
Sure, I will add the FP16S/FP16C benchmarks and look up exact model name, after I take classes.
Wait for a while please.
I will start reading your code from tommorow. Could I ask you questions again if I struggle with reading?
Acctually, I even cannot understand your code loyout becuse your code is so amaging.

**Comment by Yujif1Aero** [comment]
Hi @ProjectPhysX ,
I did these benchmarks,
FP16C;
![image](https://user-images.githubusercontent.com/116667889/201124204-53792195-7728-4979-ae5f-090ce785678c.png)

FP16S;
![image](https://user-images.githubusercontent.com/116667889/201124303-773606a5-3cfd-4237-bb81-f3851bb246ed.png)
Moreover GPU's name is here.
![image](https://user-images.githubusercontent.com/116667889/201122691-0b9a2e2e-7989-4295-b98d-ec6ab1f5ee9a.png)

Best,

**Comment by ProjectPhysX** [comment]
@Yujif1Aero thank you!!

**Comment by Yujif1Aero** [comment]
@ProjectPhysX 
I found exact GPU name, Radeon HD 7850
![IMG-1996](https://user-images.githubusercontent.com/116667889/201133460-786f734e-506e-4469-bcf0-4592ae8dfd39.jpg)
