### ISSUE TITLE
GRAPHICS_STREAMLINE_SPARSE doesn't seem to work for 2D simulations

### ISSUE THREAD

**Issue by cat5519** [ProjectPhysX/FluidX3D#41]
I've been trying some simple D2Q9 2D simulations and find that the sparse streamlines algorithm doesn't work properly. For example, using a value of 2 simply draws streamlines in the bottom half of the simulation box.  I haven't tried it with 3D simulations.

Really interesting software. Thanks for making it available.

**Comment by ProjectPhysX** [comment]
Hi @cat5519, thanks for reporting this! The bug is now fixed in update v1.4!

**Comment by cat5519** [comment]
Many thanks
