### ISSUE TITLE
MacOS build?

### ISSUE THREAD

**Issue by bcardarella** [ProjectPhysX/FluidX3D#51]
I know MacOS, especially Intel chips, aren't ideal for the GPU performance but as far as getting to play with FluidX3D before considering buying a dedicated machine for rendering it would be nice to have a MacOS build. Is that a heavy lift?

**Comment by ProjectPhysX** [comment]
Just compile it with your favourite C++ compiler on MacOS. Should work out-of-the-box, even on Apple M1/M2. Only interactive graphics probably won't work as they need WinAPI/X11.

**Comment by bcardarella** [comment]
Will give it a go, thank you

**Comment by ProjectPhysX** [comment]
Edit/update: the compiler call for MacOS is already in the file make.sh, just uncomment the line therein and run it.
