### ISSUE TITLE
Headless mode?

### ISSUE THREAD

**Issue by bcardarella** [ProjectPhysX/FluidX3D#52]
Is it possible to run in a headless mode if I have a model setup and I am more interested in getting specific output values than the visualization?

**Comment by ProjectPhysX** [comment]
Yes. Leave INTERACTIVE_GRAPHICS commented in src/defines.hpp. Depending on if you want to generate images or not, you can enable/disable GRAPHICS.

**Comment by bcardarella** [comment]
Excellent!
