### ISSUE TITLE
Userfriendly use of the program

### ISSUE THREAD

**Issue by PavelBlend** [ProjectPhysX/FluidX3D#6]
@ProjectPhysX, Hello.

Can you add the functionality of the program so that it can be used even by beginners who do not know C++.  So that the simulation can be configured via UI or json or python *.pyd library. The presence of python binding allows you to embed this engine in 3d editors that support the python api (blender, maya, 3ds max).

**Comment by MichaelRColton** [comment]
Also curious if there are plans to create a precompiled version with a gui or similar. Thanks for an awesome project!

**Comment by ProjectPhysX** [comment]
Some sort of GUI would be very nice indeed, especially also interactive graphics on Linux that are visually more appealing than the current ASCII console graphics.
I'll keep it in the back of my head, but my main priority right now is to get the multi-GPU update finished and make sure there are zero bugs. My daytime job will keep me quite busy til the end of the year, so please be patient. In the meantime, maybe take it as an incentive to learn some C++. :)
