### ISSUE TITLE
No streamlines or eddies in the f1 car example

### ISSUE THREAD

**Issue by lk251** [ProjectPhysX/FluidX3D#61]
Running everything on default settings, there were no streamlines or eddies happening anywhere around the car body, only around the tires. I experimented with grid size and other settings, to no avail.

**Comment by ProjectPhysX** [comment]
Did you remove the line from the setup that is loading the stl geometry? The stl file of the F1 car unfortunately is not available on Thingiverse anymore. Without solid geometry in the simulation domain, there will of course be no vortices.

**Comment by lk251** [comment]
thanks for the reply! i found the stl file in another website, i see the car, fuselage is in grey mesh lines, the wheels in red if i recall, only flow around the tires is visible / being computed

**Comment by ProjectPhysX** [comment]
Can you share a screenshot so I can see what is going on exactly?

**Comment by lk251** [comment]
https://media.discordapp.net/attachments/1048545964253777953/1084555640795562114/wheels_burnin.png?width=2493&height=1402

**Comment by ProjectPhysX** [comment]
Thanks! Ah! In the F1 setup there was a [line](https://github.com/ProjectPhysX/FluidX3D/commit/43b8578bbc25d39db7ede790ec6fc524adb104a5#diff-136a0cf3b22f7609379c1d6fd5eca3343bf297fb9adbb93a37dac04aefe6e520R522) commented that shouldn't have been. I just fixed this in the repo. Uncomment [line 522](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/setup.cpp#L522) in `src/setup.cpp`, then it works.

**Comment by lk251** [comment]
thank you! really enjoying this software. if you have a minute, i'm computing flow around an hp reverb g2 vr headset, can you recommend a good piece of software to convert the collection of pngs into a video file? cheers

**Comment by ProjectPhysX** [comment]
I'm using [`ffmpeg`](https://ffmpeg.org/) to convert `.png` images to `.mp4` videos. The command is:
`ffmpeg -framerate 60 -pattern_type glob -i "export/image-*.png" -c:v libx264 -pix_fmt yuv420p -b:v 80M video.mp4`. For full quality, you can remove the bitrate limitation `-b:v 60M`, but in 4K the bitrate can get so astronomically large that the video player will crash :)
