### ISSUE TITLE
Moving geometry export

### ISSUE THREAD

**Issue by DanW97** [ProjectPhysX/FluidX3D#69]
Hi,

Firstly, this is an absolutely fantastic project!

I was wondering if it is possible to export moving objects as an stl/ vtk format to better visualise moving geometries in Paraview?

Cheers,

Dan

**Comment by ProjectPhysX** [comment]
Hi @DanW97,

thank you for suggesting this feature! As part of the v2.7 release, I have now added binary `.vtk` export of the triangle mesh with `lbm.write_mesh_to_vtk(Mesh* mesh);`. This allows you to visualize the triangle mesh in the velocity field in ParaView.

Kind regards,
Moritz
