### ISSUE TITLE
Not issue: GV100 benchmark result

### ISSUE THREAD

**Issue by edmondhongkong** [ProjectPhysX/FluidX3D#7]
But where to check the TFLOPs/s
|                       ______________   ______________                       |
|                       \   ________  | |  ________   /                       |
|                        \  \       | | | |       /  /                        |
|                         \  \      | | | |      /  /                         |
|                          \  \     | | | |     /  /                          |
|                           \  \_.-"  | |  "-._/  /                           |
|                            \    _.-" _ "-._    /                            |
|                             \.-" _.-" "-._ "-./                             |
|                               .-"  .-"-.  "-.                               |
|                               \  v"     "v  /                               |
|                                \  \     /  /                                |
|                                 \  \   /  /                                 |
|                                  \  \ /  /                                  |
|                                   \  '  /                                   |
|                                    \   /                                    |
|                                     \ /                                     |
|                                      '                     ?Moritz Lehmann |
|----------------.------------------------------------------------------------|
| Device ID    0 | Quadro GV100                                               |
|----------------'------------------------------------------------------------|
|----------------.------------------------------------------------------------|
| Device ID      | 0                                                          |
| Device Name    | Quadro GV100                                               |
| Device Vendor  | NVIDIA Corporation                                         |
| Device Driver  | 516.59                                                     |
| OpenCL Version | OpenCL C 1.2                                               |
| Compute Units  | 80 at 1627 MHz (5120 cores, 16.660 TFLOPs/s)               |
| Memory, Cache  | 32767 MB, 2560 KB global / 48 KB local                     |
| Buffer Limits  | 8191 MB global, 64 KB constant                             |
|----------------'------------------------------------------------------------|
| Info: OpenCL C code successfully compiled.                                  |
|-----------------.-----------------------------------------------------------|
| Grid Resolution |                                256 x 256 x 256 = 16777216 |
| LBM Type        |                                     D3Q19 SRT (FP32/FP32) |
| Memory Usage    |                                   CPU 272 MB, GPU 1488 MB |
| Max Alloc Size  |                                                   1216 MB |
| Time Steps      |                                                        10 |
| Kin. Viscosity  |                                                1.00000000 |
| Relaxation Time |                                                3.50000000 |
| Reynolds Number |                                                  Re < 148 |
|---------.-------'-----.-----------.-------------------.---------------------|
| MLUPs   | Bandwidth   | Steps/s   | Current Step      | Time Remaining      |
|    3377 |    517 GB/s |       201 |         9996  60% |                  0s |
|---------'-------------'-----------'-------------------'---------------------|
| Info: Peak MLUPs/s = 3442                                                   |

PS D:\Software\FluidX3D> .\FluidX3D-Benchmark-FP32-FP16S-Windows.exe
.-----------------------------------------------------------------------------.
|                       ______________   ______________                       |
|                       \   ________  | |  ________   /                       |
|                        \  \       | | | |       /  /                        |
|                         \  \      | | | |      /  /                         |
|                          \  \     | | | |     /  /                          |
|                           \  \_.-"  | |  "-._/  /                           |
|                            \    _.-" _ "-._    /                            |
|                             \.-" _.-" "-._ "-./                             |
|                               .-"  .-"-.  "-.                               |
|                               \  v"     "v  /                               |
|                                \  \     /  /                                |
|                                 \  \   /  /                                 |
|                                  \  \ /  /                                  |
|                                   \  '  /                                   |
|                                    \   /                                    |
|                                     \ /                                     |
|                                      '                     ?Moritz Lehmann |
|----------------.------------------------------------------------------------|
| Device ID    0 | Quadro GV100                                               |
|----------------'------------------------------------------------------------|
|----------------.------------------------------------------------------------|
| Device ID      | 0                                                          |
| Device Name    | Quadro GV100                                               |
| Device Vendor  | NVIDIA Corporation                                         |
| Device Driver  | 516.59                                                     |
| OpenCL Version | OpenCL C 1.2                                               |
| Compute Units  | 80 at 1627 MHz (5120 cores, 16.660 TFLOPs/s)               |
| Memory, Cache  | 32767 MB, 2560 KB global / 48 KB local                     |
| Buffer Limits  | 8191 MB global, 64 KB constant                             |
|----------------'------------------------------------------------------------|
| Info: OpenCL C code successfully compiled.                                  |
|-----------------.-----------------------------------------------------------|
| Grid Resolution |                                256 x 256 x 256 = 16777216 |
| LBM Type        |                                    D3Q19 SRT (FP32/FP16S) |
| Memory Usage    |                                    CPU 272 MB, GPU 880 MB |
| Max Alloc Size  |                                                    608 MB |
| Time Steps      |                                                        10 |
| Kin. Viscosity  |                                                1.00000000 |
| Relaxation Time |                                                3.50000000 |
| Reynolds Number |                                                  Re < 148 |
|---------.-------'-----.-----------.-------------------.---------------------|
| MLUPs   | Bandwidth   | Steps/s   | Current Step      | Time Remaining      |
|    6149 |    473 GB/s |       367 |         9995  50% |                  0s |
|---------'-------------'-----------'-------------------'---------------------|
| Info: Peak MLUPs/s = 6441                                                   |

.-----------------------------------------------------------------------------.
|                       ______________   ______________                       |
|                       \   ________  | |  ________   /                       |
|                        \  \       | | | |       /  /                        |
|                         \  \      | | | |      /  /                         |
|                          \  \     | | | |     /  /                          |
|                           \  \_.-"  | |  "-._/  /                           |
|                            \    _.-" _ "-._    /                            |
|                             \.-" _.-" "-._ "-./                             |
|                               .-"  .-"-.  "-.                               |
|                               \  v"     "v  /                               |
|                                \  \     /  /                                |
|                                 \  \   /  /                                 |
|                                  \  \ /  /                                  |
|                                   \  '  /                                   |
|                                    \   /                                    |
|                                     \ /                                     |
|                                      '                     ?Moritz Lehmann |
|----------------.------------------------------------------------------------|
| Device ID    0 | Quadro GV100                                               |
|----------------'------------------------------------------------------------|
|----------------.------------------------------------------------------------|
| Device ID      | 0                                                          |
| Device Name    | Quadro GV100                                               |
| Device Vendor  | NVIDIA Corporation                                         |
| Device Driver  | 516.59                                                     |
| OpenCL Version | OpenCL C 1.2                                               |
| Compute Units  | 80 at 1627 MHz (5120 cores, 16.660 TFLOPs/s)               |
| Memory, Cache  | 32767 MB, 2560 KB global / 48 KB local                     |
| Buffer Limits  | 8191 MB global, 64 KB constant                             |
|----------------'------------------------------------------------------------|
| Info: OpenCL C code successfully compiled.                                  |
|-----------------.-----------------------------------------------------------|
| Grid Resolution |                                256 x 256 x 256 = 16777216 |
| LBM Type        |                                    D3Q19 SRT (FP32/FP16C) |
| Memory Usage    |                                    CPU 272 MB, GPU 880 MB |
| Max Alloc Size  |                                                    608 MB |
| Time Steps      |                                                        10 |
| Kin. Viscosity  |                                                1.00000000 |
| Relaxation Time |                                                3.50000000 |
| Reynolds Number |                                                  Re < 148 |
|---------.-------'-----.-----------.-------------------.---------------------|
| MLUPs   | Bandwidth   | Steps/s   | Current Step      | Time Remaining      |
|    5795 |    446 GB/s |       345 |         9991  10% |                  0s |
|---------'-------------'-----------'-------------------'---------------------|
| Info: Peak MLUPs/s = 5863

**Comment by ProjectPhysX** [comment]
Thank you very much for the benchmark results! I'll put them in the readme table soon.
I'll close this issue and create a new "issue" now where people can report benchmarks.

**Comment by ProjectPhysX** [comment]
Quick follow-up on your questions about the achieved TFLOPs:

TFLOPs/s = (MLUPs/s) * (FLOPs/step) / 10^6

where (FLOPs/step) = 326 (FP32) or 364 (FP16S) or 1241 (FP16C), counting floating-point and integer operations combined from generated PTX assembly.
In your case it's 1.12 TFLOPs/s (FP32), 2.34 TFLOPs/s (FP16S) and 7.28 TFLOPs/s (FP16C).

In all cases, the algorithm is in the bandwidth limit, so the TFLOPs/s value will always be significantly lower than device data sheet TFLOPs/s. The value is not too useful, as efficiency in bandwidth limit is determined by:

efficiency = (achieved BW) / (data sheet BW)
