### ISSUE TITLE
Capture small structure to make more real

### ISSUE THREAD

**Issue by randomwangran** [ProjectPhysX/FluidX3D#70]
I still feel we missing something to make more real. How to push the boundary more?

![image](https://user-images.githubusercontent.com/8197831/231560903-2fc6d4da-01f6-4ddb-accb-e490c100c101.png)

![image](https://user-images.githubusercontent.com/8197831/231560737-a3061f23-ff15-4ba6-9283-69ea8b68c2bb.png)

![image](https://user-images.githubusercontent.com/8197831/231560626-b943e4e8-d787-43e2-9b1e-ddd6298fb5b7.png)

Ref: https://www.youtube.com/watch?v=pZwtBEdYNIE&ab_channel=TheSlowMoGuys

**Comment by ProjectPhysX** [comment]
I know that Slow Mo Guys video, very cool! Such high-speed impacts need super high resolution to capture the microscopic droplets and at the same time the large domain overall, which in turn needs hundreds of GB of VRAM. Largest free surface simulation I've done so far is a [high-speed raindrop impact at 8 billion cells](https://youtu.be/oC6U1M0Fsug) (~2000³ grid) in 512GB VRAM across 8 MI200 GPUs. Raytracing graphics is restricted to single GPU; here is the [raindrop at 1 billion cells](https://youtu.be/VadLwt9OqMo) (~1000³ grid) with raytracing, on a single MI200 64GB.

The small feature demo in my video is at very low resolution, 0.003 billion cells (96x352x96), requiring only 170MB of VRAM. This is small enough to run interactively in real-time with fancy raytracing graphics (1x reflection, 2x refraction, 7 rays/pixel), on a 6-year-old Titan Xp GPU. Much larger resolution is possible (0.192 billion cells in 12GB) if you give the software a couple hours.

Full resolution at bullet velocity impact is still out of reach, even on a large supercomputer. 2x finer grid resolution requires 8x the VRAM capacity and 16x the compute time. FluidX3D is already optimized for smallest possible memory footprint, but I'm still having an eye on new developments. Dynamic adaptive grid refinement would be the holy grail of CFD, but is super complicated to pull off on GPU.
