### ISSUE TITLE
Please provide docker image

### ISSUE THREAD

**Issue by advanpix** [ProjectPhysX/FluidX3D#79]
This would makes your library immediately useable in cloud services, like vast.ai.

**Comment by VishalKandala** [comment]
I am a newbie when it comes to open source contributions, however I have created a docker image for the chemical kinetics solver cantera before for my research and I want to try my hand at adding this feature to this repo, would that be something I can do?

**Comment by ProjectPhysX** [comment]
Hi @advanpix,

a standard Ubuntu image is enough. Then follow the [instructions for Linux](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#linux) and you're good:
```bash
sudo apt update -y
sudo apt upgrade -y
sudo apt install nvidia-driver-535 -y
sudo apt install g++ git -y
git clone https://github.com/ProjectPhysX/FluidX3D.git
cd FluidX3D
chmod +x make.sh
./make.sh
```

@VishalKandala thanks for offering your help! But note that this is a source-available project, not open-source. I am not accepting Pull Requests.

Kind regards,
Moritz
