### ISSUE TITLE
Extract macroscopic values (Lift, Drag)

### ISSUE THREAD

**Issue by r8d8** [ProjectPhysX/FluidX3D#84]
First of all, thank you for your efforts, it's a greate piece of engineering.
Having general question, before I start digigng deeper:
Can one extract macroscopic values as lift and drag from simulation?
My intention was to use it for design of a new airframe.

**Comment by ProjectPhysX** [comment]
Hi @r8d8,

yes this is possible, see the sample setup [here](https://github.com/ProjectPhysX/FluidX3D/issues/16#issuecomment-1282276748). For low Reynolds number, surface forces are accurate to within a few %. But my testing so far indicates that at highly turbulent external aerodynamics, absolute forces are off by up to a factor 2 (too large). I'll first need to implement a wall function model to enable more accurate force readings at low-moderate resolution.

However for relative forces or ratios such as lift/drag ratio, it's already quite accurate, and might be useful to for example compare different airframe geometries.

Kind regards,
Moritz

**Comment by r8d8** [comment]
Thank you, Moritz
Exactly what I need.
