### ISSUE TITLE
missing .stl files

### ISSUE THREAD

**Issue by hpourreza** [ProjectPhysX/FluidX3D#87]
I cannot find the following stl files to run the helicopter simulation.
Bell-222-body.stl // https://www.thingiverse.com/thing:1625155/files
Bell-222-main.stl
Bell-222-back.stl

I tried to access the thingiverse website but it has only two .stl files whose names don't match the above files.

**Comment by ProjectPhysX** [comment]
Hi @hpourreza,

I'm not providing the .stl files in the repository for copyright reasons. You have to download them from the original linked sources, and for some setups edit/separate them yourself in software like [Microsoft 3D Builder](https://apps.microsoft.com/store/detail/3d-builder/9WZDNCRFJ3T6) or [Blender](https://www.blender.org/).

Kind regards,
Moritz
