### ISSUE TITLE
[Appreciting]

### ISSUE THREAD

**Issue by randomwangran** [ProjectPhysX/FluidX3D#9]
I am amazed by the power of LBM. It used to take a couple of days to
reach this level of vortical structure, but now it is just a couple of
hours.

I really appreciate your code and definitely enjoy playing with it.

![image](https://user-images.githubusercontent.com/8197831/191800496-55affdac-a2aa-4853-bf52-f2d1cc4cac65.png)

Ran

**Comment by ProjectPhysX** [comment]
You're welcome! My goal is to make lightning-fast physically accurate CFD simulations accessible to everyone on any computer.
Have fun with the code!
