### ISSUE TITLE
AMD Radeon PRO W7800

### ISSUE THREAD

**Issue by aschillingHWL** [ProjectPhysX/FluidX3D#90]
All three benchmarks with the AMD Radeon PRO W7800

<img width="592" alt="RadeonProW7900-FluidX3D-FP32-FP16S" src="https://github.com/ProjectPhysX/FluidX3D/assets/138662446/ecd97462-a2f6-413a-aed1-78fee4e7bed8">

<img width="592" alt="RadeonProW7900-FluidX3D-FP32-FP16C" src="https://github.com/ProjectPhysX/FluidX3D/assets/138662446/1bfb40c7-6003-48cc-98e9-ec1c02f97ba3">

<img width="592" alt="RadeonProW7900-FluidX3D-FP32-FP32" src="https://github.com/ProjectPhysX/FluidX3D/assets/138662446/04c73a8e-a123-4c08-83f0-34dd8bcaf30e">

**Comment by ProjectPhysX** [comment]
Thanks!!
You mean W7900, the 3-slot card with 48GB, right?
