### ISSUE TITLE
Code execution error

### ISSUE THREAD

**Issue by frontrunnin** [ProjectPhysX/FluidX3D#94]
When I try to run the program, I get this error:
![Capture](https://github.com/ProjectPhysX/FluidX3D/assets/130293657/63b98b73-1356-44ce-b35c-8b66fc1ab773)

**Comment by ProjectPhysX** [comment]
Hi @frontrunnin,

did you install [Visual Studio Community](https://visualstudio.microsoft.com/de/vs/community/) with these components?
- Desktop development with C++
- MSVC v142
- Windows 10 SDK

Kind regards,
Moritz

**Comment by frontrunnin** [comment]
Hi, I have found a workaround for this problem. Sorry for the late response
